Reorganizing Define a Data View and Get Data View Data
osisoft/OCS-Docs pull request #263
Opened 2020-09-16 21:06 UTC by osimarkrogers

Separated Recommended Workflow sections from Define a Data View and Get Data View Data, respectively.

2020-09-18 18:38 UTC, d-ng requested changes
Please fix the build errors related to broken links.
![image](https://user-images.githubusercontent.com/12798612/93633192-8f34ee00-f9bc-11ea-8e18-7ae096ee255a.png)

2020-09-18 18:59 UTC, d-ng requested changes

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +uid: RecommendedWorkflow
Since there are two recommended workflow, suggest to use a uid of DefineaDataViewRecommendedWorkflow (in PascalCase).

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +uid: RecommendedWorkflowGet
suggest to use a uid of GetDataViewDataRecommendedWorkflow (in PascalCase).

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
Can we keep the existing relationship between the headers? In other words, the sections below should be part of the procedure, and hence should be a level lower (### instead of ##).

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
(same comment on the other get data view data recommended workflow page)

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +# Recommended workflow
Since there are now two page with identical title, how about naming this one: "Recommended workflow: Define a data view".

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +# Recommended Workflow
Since there are now two page with identical title, how about naming this one: "Recommended workflow: Get Data View Data".

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +## Get data using defaults
(see other comment, use one lower level header for this and below)

2020-09-18 18:59 UTC, d-ng commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +## Specify first page parameters
Can we have all these under another header 2? 
## Overview
### Specify first page parameters
text
### Request any remaining pages
...

## Procedure: Get Data View Data
text
### Get data using defaults
text
...

2020-09-18 21:52 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +uid: RecommendedWorkflow
Changed uid's for both to DefineaDataViewRecommendedWorkflow and GetDataViewDataRecommendedWorkflow, respectively.

2020-09-21 13:58 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
That's a tough one.  The first heading in any topic is necessarily H1, and of course everything after it has to progress H2, H3, etc.  Procedures are not specifically associated with any particular heading level; it just depends on where they fall sequentially.  However, there is an issue that the OCS Writers team is currently looking at, which is the actual appearance of each heading, based on the template in use.  So this raises an interesting question: I wonder if we could/should create a heading in the template specifically for procedures, so that all procedures look the same wherever they fall.  I'll bring this up with the team and circle back with you.

2020-09-21 14:08 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +# Recommended workflow
Done.

2020-09-21 14:08 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +# Recommended Workflow
Done.

2020-09-21 14:09 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/GetDataViewData/Rec_Workflow_Get.md
> +## Get data using defaults
Headers have to progress in 1, 2, 3 order.

2020-09-21 14:58 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
I'm confused about your comment, my proposal for the headers will indeed progress from H1 -> H2 -> H3. In other words, "Procedure: Define a data view" will be H2 and "Create a data view will be H3", etc. But I guess this might be what you intended to talk about in the meeting you set up.

2020-09-21 15:06 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
Yes - - my intention was definitely to do that.  It sounds like I might have might have gotten something muddled up.

2020-09-24 16:40 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Create a data view
Heading levels should be proper now.

2020-09-29 16:12 UTC, d-ng reviewed
One final comment, rest look good.

2020-09-29 16:12 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Data view properties
Ah I must have missed it in the first review - do you find it odd that the "Data view properties" and "Related object types" are in a topic called "Recommended workflow"? I would expect only the workflow show up in this page.

2020-09-29 16:19 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Data view properties
Gotcha - - I never questioned it.  Thinking they should go into the Quick Start - Define a Data View intro....make sense? I don't think either of them are large enough to be separate topics.

2020-09-29 17:21 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Data view properties
sounds reasonable

2020-09-29 17:34 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +## Data view properties
Done.

2020-09-29 18:26 UTC, d-ng reviewed
Changing this broke some links:
![image](https://user-images.githubusercontent.com/12798612/94600359-c5e1f280-025f-11eb-86e9-6698c4b4afa8.png)

2020-09-29 19:38 UTC, d-ng approved these changes
I tried building locally, no more broken links warning.

2020-09-29 20:48 UTC, merged