Data views assets documentation
osisoft/OCS-Docs pull request #294
Opened 2020-10-20 19:23 UTC by emonino

Added asset specific documentation for data views. Note there are some links to the still hidden asset documentation. The PR unhiding the asset docs must be merged first.
Added an explanation of the Coming Soon sections to the data views overview page.
Removed language specific to data views only searching SDS streams.
Updated some outdated models and logic.

2020-10-23 18:31 UTC, osimarkrogers requested changes

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +One or more queries determine the set of data items (such as SDS streams) that the data view will include. Each [Query](xref:DataViewsQueries) should represent a collection of like data items. To inc
Change "very different items" to "very different devices"?

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Queries     | Query[] | Optional | [ ] | Queries for OCS objects (such as streams) to include in the view. This is the starting point when defining a data view. Each Query should represent a collec
Shouldn't we still be referring to "data items" rather than "objects" here? I would also change "different items" to "different devices."

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +A query for OCS objects to include in the view.
"OCS data items"?

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Keys | String[] | Optional | [ ] | Used for sources `FieldSource.PropertyId`, `FieldSource.PropertyName`, `FieldSource.Metadata` and `FieldSource.Tags`, e.g. to map to specific stream or object pro
Seems like "object" is now being applied to things referred to in previous sections as "data items".  Is there a distinction that would keep us from normalizing these?

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start_Get_Data_View_Data.md
> +By default, requests for a first page of data will cause the data view to re-resolve. See the documentation on [resolved data views](xref:ResolvedDataView#when-is-a-data-view-resolved). This ensures
Why "data items" here, and "OCS Objects" in line 15 "Resolved Data View.md"?

2020-10-23 18:31 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +- [Data items, ineligible data items, and the groups they form](xref:DataViewsDataItemsandGroups) - OCS objects retrieved by the data view query
Why using "OCS Objects" here?

2020-10-26 20:34 UTC, d-ng commented
In the resolved data view API and resolved data view preview API, we should include the changes to metadata and grouping value. I recalled we discussed about them, is this the conclusion of our discussion?

2020-10-27 01:00 UTC, d-ng commented
We also need to update GroupingValues in the Get resolved data view page.

2020-10-27 01:07 UTC, d-ng requested changes

2020-10-27 01:07 UTC, d-ng commented on Content_Portal/Documentation/DataViews/Reference/Example_Scenario.md
> +Data views are made to bring order to a tangle of data streams and other OCS objects. Despite appearing complex and verbose, this example is likely much simpler than your real-world data. This exampl
From reading it, data streams might actually be referring to stream of data rather than SDS stream. We might be able to keep it as is. What do you think?

2020-10-27 01:07 UTC, d-ng commented on Content_Portal/Documentation/DataViews/SecureDataViews/Securing_Data_Views.md
>  # Secure data views
We should probably write a section describing Data Access Control for Assets. Specifically, what happens when users request for assets that they have access to, but no access to the underlying stream.

2020-10-28 13:39 UTC, emonino commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Data_View_API.md
> +This call creates the specified data view. If a data view with the same id already exists, the existing data view is compared with the specified data view. If they are identical, a redirect (`302 Fou
Get or Create refers to the PUT HTTP verb. Like the name states, PUT will get the data view if it already exists or create the data view if it does not.

2020-10-28 13:40 UTC, emonino commented on Content_Portal/Documentation/DataViews/Data_Views_Overview.md
> +The collection(s) of OCS objects (such as streams) that a data view acts on is the result of one or more queries. Streams and other OCS objects are collectively known as *data items*. Values from the
Done

2020-10-28 13:43 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +One or more queries determine the set of data items (such as SDS streams) that the data view will include. Each [Query](xref:DataViewsQueries) should represent a collection of like data items. To inc
Data items do not necessarily represent devices. One of the major use cases for data views is working with PI to OCS streams. In that case a data item maps to a single PI tag and there are typically many PI tags per device. 

I'm open to other terminology if you can think of a better word.

2020-10-28 13:46 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Queries     | Query[] | Optional | [ ] | Queries for OCS objects (such as streams) to include in the view. This is the starting point when defining a data view. Each Query should represent a collec
I went with "OCS resources" instead or "OCS objects", but any suggestions are welcome. We can't use "data items" since Daphne is right that data items are a result of the query, not the query input. And "devices" isn't accurate since a single stream or asset doesn't necessarily represent a device.

2020-10-28 13:46 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +A query for OCS objects to include in the view.
I went with "OCS resources". See the comment above.

2020-10-28 13:47 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Keys | String[] | Optional | [ ] | Used for sources `FieldSource.PropertyId`, `FieldSource.PropertyName`, `FieldSource.Metadata` and `FieldSource.Tags`, e.g. to map to specific stream or object pro
I replaced "object" with "data item" in all cases except when referring to the input of a query.

2020-10-28 13:48 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +- [Data items, ineligible data items, and the groups they form](xref:DataViewsDataItemsandGroups) - OCS objects retrieved by the data view query
Replaced with "OCS resources". See conversation above.

2020-10-28 13:49 UTC, emonino commented on Content_Portal/Documentation/DataViews/Data_Views_Overview.md
> +Data views are subsets of data from one or more OCS sources, such as streams, which can serve as a bridge between raw OCS data and data-driven applications. A data view is a declarative query and sha
Sounds good. In addition to updating all of the "such as streams" references to say assets instead, we also need to update all the examples to reference an asset example instead of streams.

2020-10-28 13:49 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Name | Enumeration Id | Description |
Fixed

2020-10-28 13:51 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start_Get_Data_View_Data.md
> +By default, requests for a first page of data will cause the data view to re-resolve. See the documentation on [resolved data views](xref:ResolvedDataView#when-is-a-data-view-resolved). This ensures
Fixed

2020-10-28 13:52 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +	  "Kind": "Stream",
Fixed

2020-10-28 13:56 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +|PropertyId | 3 | Yes | Data from an SDS type property, found by id
I went with "SDS type property" since the field source name is "PropertyId". I could make it more generic by saying "Data from a property, found by id." or more specific - "Data from an SDS type or measurement property, found by id."

2020-10-28 13:58 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Rec_Workflow.md
> +Creating a data view begins with including some data items. This example will use SDS Streams.
The asset example I created didn't fit well with how we sprinkled references to assets throughout the documentation so I removed it. The md file is attached to the doc WI.

2020-10-28 13:58 UTC, emonino commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +			"IneligibleDataItemFields": []
Fixed

2020-10-28 13:59 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +  * Asset measurements *(Coming Soon)*: `TargetMeasurementKey` shows the measurement name
I re-worked this entire section to make it clearer.

2020-10-28 14:02 UTC, emonino commented on Content_Portal/Documentation/DataViews/SecureDataViews/Securing_Data_Views.md
>  # Secure data views
I'm hesitant to document asset specific behavior in the data views documentation because it may change. I would rather link to the asset docs from this section, but it looks like the security specific asset documentation hasn't been written yet. Let's include this in the follow up WI that will remove the stream specific language and add in the asset specific example.

2020-10-28 14:09 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* Data from each asset measurement
Fixed in the re-work of this section

2020-10-28 14:09 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +| Value | string | Static value assigned to the metadata value
Fixed

2020-10-28 14:10 UTC, emonino commented on Content_Portal/Documentation/DataViews/Reference/Example_Scenario.md
> +Data views are made to bring order to a tangle of data streams and other OCS objects. Despite appearing complex and verbose, this example is likely much simpler than your real-world data. This exampl
Sure, I just left it as data streams.

2020-10-28 14:16 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start_Get_Data_View_Data.md
> +By default, requests for a first page of data will cause the data view to re-resolve. See the documentation on [resolved data views](xref:ResolvedDataView#when-is-a-data-view-resolved). This ensures
Sure, I made it clearer that the addition/removal occurs in the underlying OCS data store.

2020-10-28 14:16 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Queries.md
> +Note that query kind defaults to Stream if not included in the query definition. A single query cannot contain both streams and assets. However, a single data view can contain both a stream query and
Fixed

2020-10-28 17:42 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +Fields of kind `DataField` map to a single [data field](xref:DataViewsFieldSets) on the data view.
Do we think the wording "map to a single" here accidentally confuses matters with the FieldMappings? (i.e. since one Field can result in multiple FieldMappings)

2020-10-28 17:42 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +|PropertyId | 3 | Yes | Data from an SDS type property, found by id
I agree with the comment and like the first suggestion

2020-10-28 17:42 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +| Uom | string | The name of the metadata value's unit of measurement
At the moment in Sds, uom Name happens to equal its Id... but strictly speaking this is the identifier, and can be used to look up the uom in Sds' api.

2020-10-28 19:19 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +|PropertyId | 3 | Yes | Data from an SDS type property, found by id
Changed to "Data from a property, found by id."

2020-10-28 19:19 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +Fields of kind `DataField` map to a single [data field](xref:DataViewsFieldSets) on the data view.
I removed the word single since it doesn't add anything and might be confusing

2020-10-28 19:20 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +| Uom | string | The name of the metadata value's unit of measurement
Sure, I corrected so it is clear that uom represents the uom identifier and not name

2020-10-28 19:26 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Queries.md
> +	"Kind": "Stream",
weird indentation for "Kind" in this file too

2020-10-28 19:26 UTC, d-ng approved these changes

2020-10-28 19:33 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Queries.md
> +	"Kind": "Stream",
I fixed the indentation in all the files.

2020-10-28 20:08 UTC, osimarkrogers approved these changes

2020-10-28 20:08 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +One or more queries determine the set of data items (such as SDS streams) that the data view will include. Each [Query](xref:DataViewsQueries) should represent a collection of like data items. To inc
No, that makes sense now.

2020-10-28 20:08 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| Queries     | Query[] | Optional | [ ] | Queries for OCS objects (such as streams) to include in the view. This is the starting point when defining a data view. Each Query should represent a collec
OCS resources is perfect.

2020-10-29 00:26 UTC, merged