Add data views units of measure docs
osisoft/OCS-Docs pull request #305
Opened 2020-11-06 15:32 UTC by d-ng

2020-11-06 16:55 UTC, osimarkrogers requested changes

2020-11-06 16:55 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +To show the units of measure within the data set, set the field's `IncludeUom` property to `true`. This apply to both data fields and group fields. In this case, the field will resolve an additional,
Possessives:  change "...set the field's IncludeUom property to true." to "...set the IncludeUom property of the field to true."

Change "This apply..." to "...This applies..."

2020-11-06 16:55 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +This simple example show a data field's `IncludeUom` property is set to `true`.
Change "This simple example show a data field's IncludeUom property..." to "The following example shows the IncludeUom property of a field is set to true."

2020-11-06 16:55 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +This simple example show how the field label token {Uom} of a data field is resolved.
Change "This simple example show..." to "The following example shows..."

2020-11-06 17:46 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| TargetMeasurementKey *(coming soon)* | The asset measurement's name. Only applicable to `PropertyId` fields and when the data field references an asset measurement. |
sure

2020-11-06 17:47 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Quick_Start_Define_a_Data_View.md
> +| IncludeUom *(Coming Soon)*| bool | Optional | false | Specifies whether to include this field's unit of measure as an additional field mapping in the resolved data view.
sure

2020-11-06 17:48 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +Data views can be configured to show the units of measure (Uom) from the underlying data source. This topic describes how units of measure is exposed in the resolved data view, as well as the differe
sure

2020-11-06 17:48 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +In the [resolved data items](xref:DataViewsDataItemsandGroups), each data item field show the unit of measure from the underlying data source. In addition, each data mapping in the [resolved field ma
changed all 3

2020-11-06 17:49 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +If the unit of measure is consistent across all groups, then that unit of measure is reported on the [field mapping](xref:DataViewsFieldMappings) itself. Otherwise, the field mapping's `Uom` property
sure

2020-11-06 17:49 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +To show the units of measure within the data set, set the field's `IncludeUom` property to `true`. This apply to both data fields and group fields. In this case, the field will resolve an additional,
fixed both

2020-11-06 17:50 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +This simple example show a data field's `IncludeUom` property is set to `true`.
changed

2020-11-06 17:50 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +This simple example show how the field label token {Uom} of a data field is resolved.
changed

2020-11-06 17:51 UTC, d-ng commented
@osimarkrogers all comments addressed, please take a look. Thanks!

2020-11-06 18:00 UTC, osimarkrogers approved these changes

2020-11-10 16:24 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +In the [resolved data items](xref:DataViewsDataItemsandGroups), each data item field shows the unit of measure from the underlying data source. In addition, each data mapping in the [resolved field m
Something like "Units of measure are shown on each data item field, as well as any corresponding data mappings where that data item field is used in the data view."?

2020-11-10 16:33 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +Data views can be configured to show the units of measure (Uom) from the underlying data source. This topic describes how to expose units of measure in the resolved data view, as well as the differen
fix in next update

2020-11-10 16:36 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +In the [resolved data items](xref:DataViewsDataItemsandGroups), each data item field shows the unit of measure from the underlying data source. In addition, each data mapping in the [resolved field m
fixed in next update

2020-11-10 16:38 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +Data views can be optionally configured to show units of measure within the data set or in labels. The [abbreviations of the units of measure](xref:unitsOfMeasure) are shown in the data view.
fixed in next update

2020-11-10 16:40 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +The field label token {Uom} can be used to add field-level unit of measure to field labels. {Uom} is included in the default field label. If the unit of measure is consistent across all groups, {Uom}
fixed in next update

2020-11-10 16:42 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +Note that the [ids of the units of measure](xref:unitsOfMeasure) are shown in resolved resources.
fixed in next update.

I'm not following what you mean by "formatting seems to be hiding it". can you elaborate?

2020-11-10 17:00 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Units_of_Measure.md
> +Note that the [ids of the units of measure](xref:unitsOfMeasure) are shown in resolved resources.
Looks good! The "formatting ... hiding" thing was just that on my screen, the suggestion text appears black, and doesn't show the cross reference hyperlink.

2020-11-10 17:04 UTC, jamesbperry approved these changes

2020-11-10 17:09 UTC, merged