Update Consent.md
osisoft/OCS-Docs pull request #307
Opened 2020-11-16 23:34 UTC by digitaljoshua

Divya, I am updating the consent topic with information about two consent email in the consent process. Please let me know if I did this correctly. I am unsure about the the verbiage in the second consent for advanced integration, as I don't have an idea what it looks like, and if there is another Consent button.

2020-11-16 23:48 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +OSIsoft Cloud Services (OCS) account. In order to proceed, you must complete the consent process to allow your OCS tenant to access your AAD tenant and directory information for authentication. This
If Advanced Integration is enabled for the AAD identity provider, then the following permissions would also need to be consented:
•	Read all users' full profiles
•	Read all group memberships

2020-11-17 00:01 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +7. At that point, this initial user will be able to use the link provided to activate his profile and sign in your OCS account.
Step number may need fixing.

2020-11-17 19:42 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +1. For a new tenant, an email will be sent to your AAD administrator who has the privileges to grant OCS access to your AAD. For an existing tenant with access to your AAD tenant, skip to step 6. Not
For my understanding, OCS 'tenant' is synonymous with OCS 'account', right?

Should we expand upon what a partially-consented state account means? For a newly created tenant that had AAD configured as the identity provider and Advanced Integration enabled, no users will be able to login to the account in a partially-consented state. For an existing tenant which already had AAD configured as an identity provider but just enabled Advanced Integration and is waiting for the consent for its required permissions, pre-existing users can still access the account while it is in the partially-consented state. New users can also still be added for the AAD identity provider, but without the features of Advanced Integration (by search).

2020-11-17 19:53 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +7. At that point, this initial user will be able to use the link provided to activate his profile and sign in your OCS account.
The way the steps are written now, they are assuming the OCS tenant is provisioned at creation with both AAD as an identity provider and Advanced Integration enabled. However, we should maybe clarify the steps to reflect the three possible paths from the starting point of a new tenant: 

1. Choosing to provision a new tenant with an identity provider which is not AAD (AAD + Advanced Integration can be added separately later).
2. Choosing to provision a new tenant with AAD as an identity provider without Advanced Integration (Advanced Integration can be added later).
3. Choosing to provision a new tenant with AAD and Advanced Integration.

For case 1, any possible future consent needed would separately be for [sign in, read profile] (AAD) and [read users' full profiles, read all group memberships] (Advanced Integration). If AAD and Advanced Integration are added separately and not at the same time, then two separate consent emails will be sent, each with one link. If they are added at the same time, then just one email with two consent links will be sent out.

For case 2, a consent email with one link will be sent when the new tenant is provisioned with AAD as an identity provider. If Advanced Integration is later added, then another email will be sent with one more link.

For case 3, one email will be sent with two consent links.

2020-11-17 19:58 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +4. Your administrator should select the box "Consent on behalf of the organization" before clicking the consent button.
I'm not sure if this has changed or if I may not be looking at the right thing, but I don't see a box to select, nor the verbiage "Consent on behalf of the organization". What I see is the following, after clicking the consent link in the email and signing in:

![image](https://user-images.githubusercontent.com/19477617/99440876-05c26f00-28cc-11eb-872a-5af476777044.png)

2020-11-17 20:03 UTC, gavchen commented on Content_Portal/Concepts/Consent.md
> +7. Your administrator should agree to the advanced integration by clicking the consent button.
As stated in the comment below for lines 12 to 20, there should just be one email with two consent links in the case that both AAD is added as an identity provider and Advanced Integration is enabled at the time of tenant creation (case 3). Cases 1 and 2 would have separate consent emails sent, but the rest of the steps should be clarified for these other 2 possible cases and flows.

I'm not sure what the agreed-upon casing is for "Advanced Integration", but I have seen it capitalized in the UI and since it is a feature name, perhaps it should be capitalized?

2020-11-17 20:09 UTC, gavchen requested changes
Thanks for writing this up! I have posted my comments - let me know if there are any questions. I also only recently learned what this flow looks like visually, so let me know if you want to go through any of it together.

2020-11-25 22:34 UTC, closed without merging

2020-11-25 22:35 UTC, digitaljoshua commented
This PR is a branch of another branch that involves restructuring of API pages which no longer will happen. therefore I created a new PR branch #309