Adding documentation for /search/assets and /bulk/asset/delete
osisoft/OCS-Docs pull request #308
Opened 2020-11-23 16:59 UTC by atangOSIsoft

Adding documentation for /search/assets and /bulk/assset/delete

2020-11-30 23:18 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +[Optional] `int skip`
Our convention is to lowercase 'optional' as in"
[optional] `int skip`

2020-11-30 23:21 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +An optional parameter representing the maximum number of assets to retrieve. If not specified, a default value of 100 is used. This value must be between (including) 1 to 1000.
Restate the first sentence: An optional parameter, between 1 and 1000 (inclusive), that represents the maximum number of assets to retrieve.
Delete the last sentence.

2020-11-30 23:45 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +An optional parameter which returns assets ordered either by the asset `Id` or the asset `name`. In addition to the property, you can optionally specify either `asc` or `desc` to return the results i
Rewrite sentence 2-3 as: Specify `asc` or `desc` to return the results in ascending or descending order. The default is ascending order.

2020-11-30 23:47 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +Returns an array of assets matching the search query and the total number of assets returned specified as Total-Count in the HTTP response header.
Returns an array of assets matching the search query. The total number of returned assets is specified as Total-Count in the HTTP response header.

2020-12-01 19:37 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +This API will search all assets and return to you a list of asset ids with their matched fields indicated in the return. This API can be used for identifying exactly which field in the asset matched
Rewrite to say: Searches all assets and returns a list of asset IDs and their matched fields. Use this API to identify the field in the asset that matched your query string. 

I'm not sure I understand how this is being used.

2020-12-01 19:46 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +An optional parameter representing the maximum number of assets to retrieve. If not specified, a default value of 100 is used. This value must be between (including) 1 to 1000.
The maximum number of retrieved assets  between 1 and 1000 (inclusive). If not specified, the default is 100.

2020-12-01 19:48 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +A list of asset ids with their matched fields indicated.
A list of asset IDs and their matched fields.

2020-12-01 19:58 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - The `MatchProperties` list contains a list of match property objects. Each match property object contains which field matched as well as the value of that field.
The `MatchProperties` list contains a list of matched property objects. Each matched property object contains the matched fields and their values.

2020-12-01 19:59 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - `Score` which indicates the relevancy of the match. The higher the score, the more relevant this asset is to your query.
`Score` indicates the relevancy of the match.

2020-12-01 20:00 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - `Id` the id of the matching asset.
`Id` Id of the matched asset

2020-12-01 20:01 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - `TypeId` the asset type id of the asset. This may be null if the asset does not reference an asset type.
`TypeId` asset type Id of the asset. This is null if the asset does not reference an asset type.

2020-12-01 20:01 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - `Name` the asset name.
`Name` asset name

2020-12-01 20:02 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +    - `Description` the asset description.
`Description` asset description

2020-12-01 20:06 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +An optional parameter representing the maximum number of assets to retrieve. If not specified, a default value of 100 is used. This value must be between (including) 1 to 100.
An optional parameter, between 1 and 1000 (inclusive), that represents the maximum number of retrieved assets. If not specified, the default is 100.

2020-12-01 20:09 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-type.md
> +An optional parameter representing the maximum number of assets to retrieve. If not specified, the default value of 100 is used. This value must be between (including) 1 to 1000.
An optional parameter, between 1 and 1000 (inclusive), that represents the maximum number of retrieved assets. If not specified, the default is 100.

2020-12-01 20:15 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +Delete all assets matching specified `Id`s. This API is used for deleting multiple assets in a given API call. Note that a maximum of 1000 assets can be deleted in a single call.
Delete all assets matching the specified `Id`s. Use this API to delete up to a maximum of 1000 assets in one API call.

2020-12-01 20:16 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| 207 Multi-Status | partial success | Array of errors. Assets that didn't encounter errors would be deleted. |
Assets that did not encounter errors are deleted.

2020-12-01 21:38 UTC, lasato-OSI requested changes
Hi @atangOSIsoft ,
Please see my changes below. If you approve the changes, I will make the changes to the files.
thanks,
Laureen

2020-12-02 16:37 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `Score` which indicates the relevancy of the match. The higher the score, the more relevant this asset is to your query.
Score - number that indicates the relevancy of the match.

2020-12-02 16:38 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `Id` the id of the matching asset.
Id - Id of the matched asset

2020-12-02 16:39 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `TypeId` the asset type id of the asset. This may be null if the asset does not reference an asset type.
Type Id - the asset's asset type Id. This is null if the asset does not reference an asset type. 

Will it always be null or only some times?

2020-12-02 16:40 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `Name` the asset name.
Name - asset name

2020-12-02 16:40 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `Description` the asset description.
Description - asset description

2020-12-11 00:51 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +- `TypeId` the asset type id of the asset. This may be null if the asset does not reference an asset type.
The typeId will only be null if the asset does not contains an asset type.

2020-12-11 00:51 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +Returns an array of assets matching the search query and the total number of assets returned specified as Total-Count in the HTTP response header.
Thanks!

2020-12-11 08:11 UTC, atangOSIsoft commented
> Hi @atangOSIsoft ,
> Please see my changes below. If you approve the changes, I will make the changes to the files.
> thanks,
> Laureen

Hi Laureen, the suggested changes look great to me. Thanks!

2020-12-15 00:52 UTC, lasato-OSI approved these changes

2020-12-15 00:55 UTC, lasato-OSI commented
Adding documentation for /search/assets and /bulk/asset/delete.

2020-12-15 00:55 UTC, merged