Summary doc
osisoft/OCS-Docs pull request #322
Opened 2020-12-16 21:40 UTC by BethZelasky

2020-12-17 14:28 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| SummaryType *(coming soon)* | The summary type calculation for the data field. Not applicable to `Id`, `Name`,`Metadata` or `Tags` fields. |
Really minor but it looks like you are missing a space between name and metadata.
What do you think about "Only applicable to 'PropertyId' and 'PropertyName' fields."? It is a little shorter.

2020-12-17 14:29 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| SummaryType *(coming soon)* | Not applicable|
Why add only SummaryType and not SummaryDirection? Both are not applicable so it would seem to make sense to add both or neither.

2020-12-17 14:32 UTC, emonino commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +| SummaryType *(coming soon)* | SdsSummaryType  |The summary type calculation. |
Should we mention these are null unless all the data mappings are identical? See uom below.

2020-12-17 14:37 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Summary types are treated as a platform intrinsic, as is done by Sds and Assets. A stream and its properties provide no information about what summaries are available for each property;
I don't know if this level of detail is required for the data views documentation. Seems like a better fit for SDS. I think simply saying summary values that do not apply will be null is sufficient.

2020-12-17 14:40 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +In the data view a field defines the type of summary with the SummaryType property as [SdsSummaryType](https://ocs-docs.osisoft.com/Content_Portal/Documentation/SequentialDataStore/Reading_Data_API.h
I wish there was more detail about summary direction. Perhaps an example would be useful? I just think saying "SummaryDirection controls whether the start or end index of the summary is used by the data view to calculate the summary values" is not enough to fully grasp what SummaryDirection means if you are new to data views.

2020-12-17 14:45 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](https://ocs-docs.osisoft.com/C
I think we are supposed to use the hyperlinks from the top of each page when generating links in our docs now so this should be xref:sdsReadingDataApi#get-summaries

2020-12-17 17:42 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| SummaryType *(coming soon)* | Not applicable|
Although your point is correct, I didn't add SummaryDirection? the Index field is automatically inserted into the data view by default and it is not there, see below, & I did not want to confuse.  
"IndexField": {
        "Source": "NotApplicable",
        "Keys": [],
        "MeasurementKeys": [],
        "Label": "Timestamp",
        "SummaryType": "None",
        "IncludeUom": false
    }

2020-12-17 17:50 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/GetResolvedDataView/Resolved_Data_View.md
> +| SummaryType *(coming soon)* | SdsSummaryType  |The summary type calculation. |
Sure

2020-12-17 17:51 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| SummaryType *(coming soon)* | The summary type calculation for the data field. Not applicable to `Id`, `Name`,`Metadata` or `Tags` fields. |
Good idea!

2020-12-17 17:53 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](https://ocs-docs.osisoft.com/C
thank you

2020-12-17 18:06 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Summary types are treated as a platform intrinsic, as is done by Sds and Assets. A stream and its properties provide no information about what summaries are available for each property;
OK

2020-12-17 20:26 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +In the data view a field defines the type of summary with the SummaryType property as [SdsSummaryType](https://ocs-docs.osisoft.com/Content_Portal/Documentation/SequentialDataStore/Reading_Data_API.h
Added a little example

2020-12-17 20:41 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](https://ocs-docs.osisoft.com/C
You missed this SdsSummaryType link.

2020-12-17 20:47 UTC, emonino commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +This example shows the impact of SummaryDirection, and how changing it will shift the summary value calculation. Three mini data view results are shown, where SummaryType and SummaryDirection are var
Can we explicitly state the forward mean value at 2 is from 2 to 3, hence it is the mean of the all the values between those two times. This kind of looks like it is only the mean of the 2 values at the start and end index.

2020-12-18 13:52 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](https://ocs-docs.osisoft.com/C
Fixed

2020-12-18 13:53 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +This example shows the impact of SummaryDirection, and how changing it will shift the summary value calculation. Three mini data view results are shown, where SummaryType and SummaryDirection are var
I added more explanation

2021-01-07 16:24 UTC, osimarkrogers requested changes

2021-01-08 14:18 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Mappings.md
> +| SummaryType *(coming soon)* | The summary type calculation for the data field. Only applicable to 'PropertyId' and 'PropertyName' fields. |
Fixed.

2021-01-08 14:18 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Not all SDS properties will have summaries. For example a string property cannot have a Mean. If a data item field requests a summary that is unavailable these values will be null in the view data.
Fixed

2021-01-08 14:20 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +This simple example shows the inclusion of a summary data field for a SummaryType set to "Mean" and "IncludeUom" is set to "true". Since the SummaryDirection is not set, the default value of "Forward
fixed

2021-01-08 14:21 UTC, BethZelasky commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +This simple example shows the inclusion of a summary data field for a SummaryType set to "Mean" and "IncludeUom" is set to "true". Since the SummaryDirection is not set, the default value of "Forward
Fixed both.

2021-01-13 15:28 UTC, osimarkrogers approved these changes

2021-01-13 15:29 UTC, merged