OCS Conceptual Docs - Functionality (What does OCS do?)
osisoft/OCS-Docs pull request #325
Opened 2020-12-22 21:35 UTC by osisoft-ezrinsky

This branch contains all of the changes to the OCS conceptual documentation since the last merge. This includes a new topic called "What does OCS do?" which covers all of the high-level functionality available in the OCS platform.

2021-01-04 18:55 UTC, jgolla commented on Content_Portal/Overview/what-does-ocs-do.md
> +A type can consist of many properties, but one property must function as the primary index. Time is frequently used as the primary index, effectively time-stamping all corresponding properties in eac
`it can be any sequential data, such depth or movement` ... I am confused by the term movement. I don't know what movement is or how it is sequential?

2021-01-04 20:50 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides many configuration and control options that allow administrators to customize interactions with the platform based on organizational requirements. Administrators can create users and cli
@digitaljoshua I think we should do X here.

2021-01-04 20:56 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +* [Tenant management](#tenant-management) - Explains basic concepts in managing OCS, including clients, roles and metadata and discusses how administrators can customize OCS based on organizational r
Feedback from @kchudnovskiy: I’m not sure what “metadata” refers to here, it’s a bit ambiguous while clients, roles, are concrete concepts. Metadata is used again in line

2021-01-04 20:56 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides many configuration and control options that allow administrators to customize interactions with the platform based on organizational requirements. Administrators can create users and cli
Feedback from @kchudnovskiy: but probably for something different.

2021-01-04 20:57 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +* Manage and authenticate client applications
Feedback from @kchudnovskiy: I’m not sure what it means for an identity to “manage” a client application.

2021-01-04 20:57 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A user is an individual identity that represents a person using OCS. When users log in to OCS, they authenticate through an identity provider such as Google or Azure Active Directory. The identity pr
Feedback from @kchudnovskiy: “granting the user access for a specific time period” is a little misleading because the identity provider only verifies the identity of the user, it does not have anything to do with granting access. Perhaps “identifying a user for a specific time period”?

2021-01-04 20:57 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Clients are applications and PI Adapters that act on behalf of users and have programmatic access by using OCS APIs. OCS supports the following client types:
Feedback from @kchudnovskiy: Calling out PI Adapaters especially seems strange.

2021-01-04 20:58 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A role is a representation of a user’s job function that determines whether the user can have access to resources needed to accomplish a job. You can assign multiple roles to a user or client-credent
Feedback from @kchudnovskiy: Instead of “a user’s job function” maybe “identity’s job function”? Also, at least from the UI workflow perspective it would be “assigns those roles to users and clients” instead of “assigns users and clients to those roles”.

2021-01-04 20:58 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +For both users and clients, roles authorize API requests for access, such as access to data streams. All clients have the Access Member role, which provides read access to resources.
Feedback from @kchudnovskiy: I think the role is “Tenant Member” not “Access Member” (unless this changed recently).

2021-01-04 20:58 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Identity providers manage databases of user records and authenticate users against the credentials in their databases. This allows users to be granted access to the service provider using the credent
Feedback from @kchudnovskiy: Instead of “sharing actual login details” maybe “sharing actual login details with OCS”?

2021-01-04 20:59 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Authentication is the process of verifying the identity of a user or client and confirming that the requestor is an approved entity for OCS. This verification process is performed by the identity pro
Feedback from @kchudnovskiy:  Client access does not go through an identity provider. We store the client credentials in OCS.

2021-01-04 20:59 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +
Feedback from @kchudnovskiy: I think steps 2 and 3 can be combined to remove “Gateway” since that’s an internal detail. Can just be “OCS does not recognize the requestor and makes a request to an identity service”.

2021-01-04 21:00 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +5.	The identity service sends an authentication request to a third-party identity provider along with the user credentials.
Feedback from @kchudnovskiy: This makes it sound like the identity service has the user’s credentials. I believe this whole workflow occurs directly with the identity provider.

2021-01-04 21:00 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	A gateway service examines the access token of the requestor to validate the token.
Feedback from @kchudnovskiy: Again discussing the gateway here may be too much internal detail. Maybe combine steps 2 and 3 into “OCS examines the access token of the requestor to validate the token and routes the request to the appropriate OCS service.” In the following line I would also distinguish a service (responsible for managing a resource) from a resource (the item the user is interacting with).

2021-01-04 21:50 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +
Feedback from @kchudnovskiy: Agree with David. This is internal implementation that should not be documented. What if we changed something here? It would not affect users.

2021-01-04 21:51 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OSIsoft Message Format (OMF) is a platform-independent format for passing JSON messages to OCS using an HTTP client.
Feedback from @kchudnovskiy: “using an HTTP client” maybe should just be “over HTTP”? They don’t have to use any specific client.

2021-01-04 21:51 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +
Feedback from @kchudnovskiy: Internal implementation

2021-01-04 21:52 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The OCS programmatic REST API reads and writes data. It supports JSON files and platform independence with platform-independent data and retrieval.
Feedback from @kchudnovskiy: “It supports JSON files … “. I am not sure what this sentence is trying to convey. Maybe “JSON format” instead of “JSON files”?

2021-01-04 21:53 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +After setting up data collection, you can use the Sequential Data Store (SDS) to store, retrieve, and analyze any type of streaming data. Typically, developers use the SDS to create customized applic
Feedback from @kchudnovskiy:  Instead of “use the SDS to create customized applications” maybe “use SDS as part of their customized applications”?

2021-01-04 21:54 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides a simple user interface for creating types. Alternatively, you can create types using programming tools provided by OSIsoft. For an automated programmatic approach, OSIsoft offers .NET c
Feedback from @kchudnovskiy: Instead of “if no other streams, views, …” should be “if no streams, views, …”.

2021-01-04 21:54 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +There are two sources of data for streams:
Feedback from @kchudnovskiy: 192-195 -  I’m not sure why there is a distinction from the OCS point of view. You send data to SDS and then it is available in SDS.

2021-01-04 21:55 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Each stream is associated with a namespace. You can associate one or more streams with the same namespace. However, to move data between namespaces, you must read data out from one namespace and read
Feedback from @kchudnovskiy:  “you must read data out from one namespace and read it back into another namespace” should be “write it into another namespace”.

2021-01-04 21:55 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +For example, a process engineer and a maintenance technician, might want to see different data from the same stream. Because you cannot change the data sent to a stream, a stream view allows you to s
Feedback from @kchudnovskiy: Instead of “cannot change the data sent to a stream” maybe “cannot change the shape of data belonging to a stream”.

2021-01-04 21:55 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
Feedback from @kchudnovskiy:  The example is way more detailed than others in the doc.

2021-01-04 22:07 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OSIsoft Cloud Services (OCS) consists of several different areas of core functionality:
Feedback from David Moler:  this refers to OCS, but the bullet points are about the documentation, not OCS directly

2021-01-04 22:08 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Using access control lists (ACLs), administrators can also limit permissions to a resource. Generally, only administrators should have access to tenant management features. Administrators can perform
Feedback from David Moler: (near end): this is phrased in a way that makes OCS portal sound like it is focused on tenant admin functions - it does that but also many other things.

2021-01-04 22:09 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A tenant represents a set of services, applications, data, and available configuration states. You can authenticate users for a tenant by using one or more identity providers. You can manage user acc
Feedback from David Moler: This section seems confusing. Maybe it something like:
A tenant is the root-level resource in OCS; all other resources are scoped to a tenant. Tenant-level resources deal with identity and access control. You can add users to a tenant using one or more identity providers. Roles are defined for a tenant and can be assigned to users or clients to manage access to resources. A tenant contains namespaces where data is managed.

2021-01-04 22:18 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A namespace is a logical unit of organization for data within a tenant. Before any data can be collected in OCS, you must create a namespace for that tenant. Each tenant can contain more than one nam
Feedback from David Moler: : This part isn't quite right: "Namespaces help you create separate instances of your data and resources in OCS so one tenant does not affect other tenants." Namespaces let you separate instances since 1 namespace won't affect another. Tenants don't contain data and never affect each other (these are likely different customers). We might also mention here that namespaces control the geographic location of data - namespace data lives in a particular geographic region.

2021-01-04 22:20 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The concept of identity is the key to how OCS limits and protects services and resources available to an entity. An entity’s identity allows OCS to know how much access to grant to that entity. OCS i
Feedback from David Moler: I don't think "protect data resources" belongs here - identity authenticates the entity, but doesn't do any enforcement of access policy.

2021-01-04 22:21 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A user is an individual identity that represents a person using OCS. When users log in to OCS, they authenticate through an identity provider such as Google or Azure Active Directory. The identity pr
Feedback from David Moler: I'm not sure we should make this statement: "The identity provider authenticates the user against credentials stored in its database" since this is managed by a 3rd party. Who are we to say how Google authenticates people?

2021-01-04 22:22 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Clients are applications and PI Adapters that act on behalf of users and have programmatic access by using OCS APIs. OCS supports the following client types:
Feedback from David Moler: There are 2 primary types of clients: Client Credentials: applications like PI Adapters or web applications that act on behalf of a user. Users will likely use the 1st type many times. They may never use the 2nd type. I don't think we should even document Hybrid clients since this is an old approach that is no longer recommended. Auth code clients are the 2nd type but deserve less emphasis than client credential clients. These are grouped together because of the Identity Server, from a user perspective these are very different concepts.

2021-01-04 22:22 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authentication
Feedback from David Moler: this feels like it belongs in developer/api documentation, not a conceptual doc. I suggest removing this whole section.

2021-01-04 22:22 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authorization
Feedback from David Moler: Authorization - ditto this section - it belongs in developer documentation, not a conceptual doc.

2021-01-04 22:23 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Access control list
Feedback from David Moler: Could expand this with the rights we support: Read, Write, Delete, Manage Access Control. We also have an Owner which has full rights on the object. The Owner is an identity but the access control is granted to Roles, not users.

2021-01-04 22:24 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Group
Feedback from David Moler:  We call these Roles in OCS, not groups. Groups are defined in an identity provider like AAD and can be mapped to a role. I recommend removing this section but expanding on the previous section with details about roles & owners.

2021-01-04 22:24 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Tenants may contain data across multiple geographic locations; however, in order to remain compliant with local laws and regulation, a namespace can contain or collect data for a specific region only
Feedback from David Moler:  Wording here is confusing: "Tenants may contain data across multiple geographic locations; however, in order to remain compliant with local laws and regulation, a namespace can contain or collect data for a specific region only. " A tenant doesn't contain data, but a tenant can contain namespaces hosted in different regions. OCS doesn't do any compliance for the customer - we allow people to store stuff from any region. What we do is scope namespaces to regions so our customers can comply with local laws and regulations by controlling where their data is hosted.

2021-01-04 22:25 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	Gateway passes request to proper partition of PI to OCS based on tenant ID in the token. Roles associated with the client are included in the request header.
Feedback from David Moler: 109-111-  do users really care how this is implemented?

2021-01-04 22:26 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OMF topics aggregate OMF messages received from one or more clients and make them available for consumption by a subscription. An OMF subscription consumes OMF messages from a topic and forwards them
Feedback from David Moler: Remove "by a subscription" in the 1st sentence?

2021-01-04 22:27 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OMF itself does not define or depend on any binary message protocol, such as HTTP, AMQP, or Kafka. Instead, it is based on an abstract message type, where a message consists of a set of key/value pai
Feedback from David Moler: "set of key/value pairs and a binary payload," with "set of key/value pairs,"

2021-01-04 22:28 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	A gateway passes the request to the proper partition of OMF collection based on a tenant ID in the token. Roles associated with the client are included in the request header.
Feedback from David Moler: 122-124: does a user really care? This is internal OCS implementation.

2021-01-04 22:28 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	A gateway passes the request to the Sequential Data Store.
Feedback from David Moler: user shouldn't care

2021-01-04 22:29 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +A type can consist of many properties, but one property must function as the primary index. Time is frequently used as the primary index, effectively time-stamping all corresponding properties in eac
Feedback from David Moler: If we mention a secondary index, we should explain it at least a little.

2021-01-04 22:29 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +After you create a type, you cannot change it. If you want to change a type, you must delete the existing type and create a new one. However, you can only delete a type if no other streams, views, or
Feedback from David Moler: We should justify this somewhat - we could say that we don't want to invalidate data already stored so data needs to be explicitly migrated to a different type to remove/recreate a type.

2021-01-04 22:29 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +There are two sources of data for streams:
Feedback from David Moler: 192-195 - I don't understand what this is trying to say.

2021-01-04 22:30 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
Feedback from David Moler:  this example is much more detailed that what is covered in other parts of the document. Elsewhere we've only covered capabilities, not very specific examples.

2021-01-04 23:52 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +A namespace is a logical unit of organization for data within a tenant. Before any data can be collected in OCS, you must create a namespace for that tenant. Each tenant can contain more than one nam
this isn't that clear: Namespaces help you create separate instances of your data and resources in OCS so one tenant does not affect other tenants.  I would change to: Namespaces help you create separate instances of your data and resources within a tenant, and resources within a namespace do not affect other namespaces within that tenant.

2021-01-05 00:02 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authorization
agreed. seems redundant here.

2021-01-05 00:05 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	Gateway passes request to proper partition of PI to OCS based on tenant ID in the token. Roles associated with the client are included in the request header.
I agree with David, everthing starting from "In the diagram below is not needed. However, perhaps we could add a link to the PI to OCS help documentation?

2021-01-05 00:06 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	A gateway passes the request to the proper partition of OMF collection based on a tenant ID in the token. Roles associated with the client are included in the request header.
Agreed.

2021-01-05 00:06 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +Tenants may contain data across multiple geographic locations; however, in order to remain compliant with local laws and regulation, a namespace can contain or collect data for a specific region only
Agreed, doesn't make sense the way it is written

2021-01-05 00:11 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +There are two sources of data for streams:
192-195 - agreed, it is confusing - this is where the API documentation is a bit more clear what a data stream - those definitions are good; https://ocs-docs.osisoft.com/Content_Portal/Documentation/SequentialDataStore/Data_Store_and_SDS.html

2021-01-05 00:13 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +Stream views can perform additional functions, such as to implement data conversions and change names so the terminology that is displayed is more appropriate for a particular persona.
implement data conversions - you mean unit of measure converstions?

2021-01-05 00:22 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
I personally like the detail - it helps the newbie understand metadata rules and Dataviews

2021-01-05 00:23 UTC, rachnahanda commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
I like the details though

2021-01-05 14:07 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +A type can consist of many properties, but one property must function as the primary index. Time is frequently used as the primary index, effectively time-stamping all corresponding properties in eac
If no one has a better explanation, I will reword to "any sequential data, such as depth."

2021-01-05 14:09 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +After you create a type, you cannot change it. If you want to change a type, you must delete the existing type and create a new one. However, you can only delete a type if no other streams, views, or
rewrite to "you must delete the existing type and create a new on to ensure that no stored data is invalidated."

2021-01-05 14:59 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Tenants may contain data across multiple geographic locations; however, in order to remain compliant with local laws and regulation, a namespace can contain or collect data for a specific region only
Sounds good. Removing that sentence entirely. It seems like we addressed what a tenant is and does in early sections.

2021-01-05 15:23 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	Gateway passes request to proper partition of PI to OCS based on tenant ID in the token. Roles associated with the client are included in the request header.
Good feedback. Removed the instruction and diagram. Waiting on a link for PI to OCS.

2021-01-05 15:23 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +
Resolved. Removed instructions and image.

2021-01-05 15:24 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OSIsoft Message Format (OMF) is a platform-independent format for passing JSON messages to OCS using an HTTP client.
Changed to suggested language.

2021-01-05 15:25 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OMF topics aggregate OMF messages received from one or more clients and make them available for consumption by a subscription. An OMF subscription consumes OMF messages from a topic and forwards them
Removed suggested language.

2021-01-05 15:26 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OMF itself does not define or depend on any binary message protocol, such as HTTP, AMQP, or Kafka. Instead, it is based on an abstract message type, where a message consists of a set of key/value pai
Removed suggested language.

2021-01-05 15:26 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	A gateway passes the request to the proper partition of OMF collection based on a tenant ID in the token. Roles associated with the client are included in the request header.
Removed diagram and image.

2021-01-05 15:27 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +
Removed diagram and text.

2021-01-05 15:29 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The OCS programmatic REST API reads and writes data. It supports JSON files and platform independence with platform-independent data and retrieval.
Changed suggested language and removed "platform independence with." Also removed diagrams and instructions from the PI Adapters and EDS sections for consistancy.

2021-01-05 15:30 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	A gateway passes the request to the Sequential Data Store.
Removed diagram and instructions.

2021-01-05 17:58 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides a simple user interface for creating types. Alternatively, you can create types using programming tools provided by OSIsoft. For an automated programmatic approach, OSIsoft offers .NET c
Done

2021-01-05 17:59 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +There are two sources of data for streams:
I removed those sentences

2021-01-05 17:59 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +There are two sources of data for streams:
I removed those sentences

2021-01-05 18:00 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +Each stream is associated with a namespace. You can associate one or more streams with the same namespace. However, to move data between namespaces, you must read data out from one namespace and read
Done. Good catch!

2021-01-05 18:02 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +Stream views can perform additional functions, such as to implement data conversions and change names so the terminology that is displayed is more appropriate for a particular persona.
Yes, that's what I meant. Change made.

2021-01-06 18:26 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +* [Tenant management](#tenant-management) - Explains basic concepts in managing OCS, including clients, roles and metadata and discusses how administrators can customize OCS based on organizational r
Agreed. Metadata isn't even discussed in this section. I removed it, and added concepts we do discuss in this section such as users and roles-based access control.

2021-01-06 18:35 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides many configuration and control options that allow administrators to customize interactions with the platform based on organizational requirements. Administrators can create users and cli
I think this seems out of place here. I am removing "metadata".

2021-01-06 18:39 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +* Manage and authenticate client applications
Manage is not really applicable, I agree. I will remove "manage and"

2021-01-06 18:52 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +A user is an individual identity that represents a person using OCS. When users log in to OCS, they authenticate through an identity provider such as Google or Azure Active Directory. The identity pr
I can reword this so it doesn't imply that the IdP is granting anything.

2021-01-06 18:59 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Clients are applications and PI Adapters that act on behalf of users and have programmatic access by using OCS APIs. OCS supports the following client types:
Agreed. I think this was introduced after writing. PI Adapter is a type of client, mentioned below as an example. I removed "PI Adapter" from the sentence.

2021-01-06 19:04 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +A role is a representation of a user’s job function that determines whether the user can have access to resources needed to accomplish a job. You can assign multiple roles to a user or client-credent
Modified as suggested.

2021-01-06 19:06 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +For both users and clients, roles authorize API requests for access, such as access to data streams. All clients have the Access Member role, which provides read access to resources.
Corrected.

2021-01-06 19:07 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Identity providers manage databases of user records and authenticate users against the credentials in their databases. This allows users to be granted access to the service provider using the credent
Modified as described

2021-01-06 19:17 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +
changed the "users or clients" to "requestor"

2021-01-06 19:20 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Authentication is the process of verifying the identity of a user or client and confirming that the requestor is an approved entity for OCS. This verification process is performed by the identity pro
changed "users or clients" to "requestor" for now

2021-01-07 00:36 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +
modified as suggested.

2021-01-07 00:40 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +5.	The identity service sends an authentication request to a third-party identity provider along with the user credentials.
Reworded as follows to imply everything is done with the identity provider:

1.	A requestor makes a request to access an OCS resource. 
2.	OCS does not recognize the requestor and makes a request to an identity provider.
4.	The identity provider asks the user which account/credentials should be used to connect. 
5.	The authentication request along with the user credentials is received by the identity provider. 
6.	The identity provider verifies the user credentials with its corresponding database. 
7.	After successful verification, the identity provider passes an access token for the user back to the identity service. This access token grants the user a limited period of access.

2021-01-07 00:42 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	A gateway service examines the access token of the requestor to validate the token.
Reworded to imply the service is managing the granting of access: 

1.	The requestor sends a request to an OCS resource. 
2.	OCS examines the access token of the requestor to validate the token and routes the request to the appropriate OCS service.
4.	The service responsible for the OCS resource examines the user’s assigned role and correlates the role against its access control list. The ACL defines an access level to the resource for each role. 
5.	The resource grants that level of access to the user.

2021-01-07 00:47 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +OSIsoft Cloud Services (OCS) consists of several different areas of core functionality:
[For writers] How should we reword this? I took a brief stab: 

OSIsoft Cloud Services (OCS) consists of several different areas of core functionality: Tenant management, data collection, data organization, and data analysis. The following sections discuss each in detail, as listed:

* [Tenant management](#tenant-management) - Explains basic concepts in managing OCS, including clients, users, roles, roles-based access control and discusses how administrators can customize OCS based on organizational requirements 
* [Data collection](#data-collection) - Summarizes techniques to collect and feed data from multiple sources across your organization into a namespace within OCS 
* [Data organization](#data-organization) - Provides a high-level description of how OCS stores and retrieves operational data 
* [Data analysis](#data-analysis) - Highlights some of the capabilities of using OCS for data analysis, which enables informed planning, predictive maintenance, and operational optimization

2021-01-07 00:49 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Using access control lists (ACLs), administrators can also limit permissions to a resource. Generally, only administrators should have access to tenant management features. Administrators can perform
[REQUIRES FEEDBACK] on what else to list.

2021-01-07 00:51 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +A tenant represents a set of services, applications, data, and available configuration states. You can authenticate users for a tenant by using one or more identity providers. You can manage user acc
Changed as suggested.

2021-01-07 00:54 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +A namespace is a logical unit of organization for data within a tenant. Before any data can be collected in OCS, you must create a namespace for that tenant. Each tenant can contain more than one nam
Replaced offending sentence with Rachna's suggestion.

2021-01-07 00:56 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +The concept of identity is the key to how OCS limits and protects services and resources available to an entity. An entity’s identity allows OCS to know how much access to grant to that entity. OCS i
Removed.

2021-01-07 00:57 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +A user is an individual identity that represents a person using OCS. When users log in to OCS, they authenticate through an identity provider such as Google or Azure Active Directory. The identity pr
Removed that part.

2021-01-07 01:02 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Clients are applications and PI Adapters that act on behalf of users and have programmatic access by using OCS APIs. OCS supports the following client types:
[VERIFY with SMEs] 

Clients have programmatic access to OCS resources through using OCS APIs. There are two primary client types: 

* **Client credential clients** – Used for server-to-server communication without the presence or intervention of a user. Examples include PI Adapters or the Edge Data Store sending data to OCS. This type of client is issued a client ID and secret. After authentication, the client is granted an access token with a defined lifetime. 

* **Authorization code clients** – Used by web-based, mobile, and desktop applications, this client type requires user interaction. Users authenticate with an identity provider. Authorization code clients support silent refresh, which allows the user to automatically receive a new access token, providing for uninterrupted access to the application.

2021-01-07 01:03 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authentication
[VERIFY removing this section entirely]

2021-01-07 01:03 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authorization
[VERIFY removing this section entirely]

2021-01-07 01:08 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Access control list
[VERIFY with SME] 

The types of permissions granted to roles are as follows:
* Read
* Write
* Delete
* Manage Access Control: Ability to modify the access control list of the resource.
* Owner: An identity that has full permission level.

2021-01-07 01:10 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Group
Removed Groups.

2021-01-11 20:36 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Using access control lists (ACLs), administrators can also limit permissions to a resource. Generally, only administrators should have access to tenant management features. Administrators can perform
Tenant resources are a narrow aspect of OCS functionality. Very admin focussed stuff. Most of what customers will use the portal with is for Namespace resources, streams and assets.

2021-01-11 20:38 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authentication
Highly specific and developer-focused. Might be a different audience than the rest of the document.

2021-01-11 20:40 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authentication
This might be better for developer documentation but might be too confusing and misleading for other users.

2021-01-11 20:43 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Access control list
An administrator could assign these perms and this might be useful information to include

2021-01-12 16:12 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +5.	The identity service sends an authentication request to a third-party identity provider along with the user credentials.
removed this part as part of feedback from David M

2021-01-12 16:13 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	A gateway service examines the access token of the requestor to validate the token.
removed these details as part of suggestion from David M.

2021-01-13 19:26 UTC, elizabeth112 commented on Content_Portal/Overview/what-does-ocs-do.md
> +Three methods are available in OCS, each of which works dynamically, continuing to filter and order data after they are in place. These methods include the following:
Three should be two now with the removal of trending from this section?

2021-01-13 19:27 UTC, elizabeth112 commented on Content_Portal/Overview/what-does-ocs-do.md
> +  Metadata rules simplify the task of collecting and retrieving data streams.
Metadata rules aren't involved in data collection, so this point doesn't make sense to me.

2021-01-13 19:30 UTC, elizabeth112 commented on Content_Portal/Overview/what-does-ocs-do.md
> +Metadata rules enable users to capture data streams based on specific stream name parts, such as a plant location or device category.  A metadata rule captures all streams in a given namespace that m
"enable users to capture data streams"...this doesn't sound right. Metadata rules enable users to create metadata in bulk via patterns in their streams. This metadata then facilitates the grouping and organization of their data.

2021-01-13 19:36 UTC, elizabeth112 commented on Content_Portal/Overview/what-does-ocs-do.md
> +Data views serve as a bridge between raw OCS data and data science applications. Users can use an API to programmatically align and interpolate data in data views for the purpose of doing advanced an
Can you clarify the intent of including this line "Data views mesh neatly with OSIsoft’s larger data science enablement efforts"...I'm not sure it's needed.

2021-01-13 19:38 UTC, elizabeth112 commented on Content_Portal/Overview/what-does-ocs-do.md
> +  **Note: You can reference a metadata rule to create a data view. By doing so, the data view includes all the streams captured by the referenced metadata rule.
Data views do not reference metadata rules. Metadata rules create metadata on streams. Stream metadata can then be used when searching for streams to include in a data view or as part of the data fields to include in a data view.

2021-01-13 21:17 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
Reduced detail to normalize topic coverage.

2021-01-13 21:44 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +  **Note: You can reference a metadata rule to create a data view. By doing so, the data view includes all the streams captured by the referenced metadata rule.
I was mistaken in saying you can reference a metadata rule, rather than referencing assigned metadata to locate streams to include in a data view. Changed to "You can reference metadata defined in a metadata rule when creating a data view. This action will include all streams containing the specified metadata."

2021-01-13 21:47 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +Metadata rules enable users to capture data streams based on specific stream name parts, such as a plant location or device category.  A metadata rule captures all streams in a given namespace that m
Changed metadata rules discussion to talk only about assigning metadata. Removed instances of "capturing".

2021-01-13 21:50 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +  Metadata rules simplify the task of collecting and retrieving data streams.
Changed to "Metadata rules enable users to assign metadata to selected parts of defined stream name patterns."

2021-01-15 20:12 UTC, afloresOSI requested changes
I think the overall structure is good. I have indicated a number of places that could be more clear.

2021-01-15 20:12 UTC, afloresOSI commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	A user creates a data view in OCS based on streams containing the specified metadata, selects specific data elements from the streams, and orders and indexes them as needed.
You create... (don't use "user")

2021-01-15 20:12 UTC, afloresOSI commented on Content_Portal/Overview/what-does-ocs-do.md
> +Data views allow you to arrange data fields in a way that they can be consumed by a third-party data science application.
Remove this sentence.

2021-01-15 20:12 UTC, afloresOSI commented on Content_Portal/Overview/what-does-ocs-do.md
> +In addition to being applied to any existing streams, a metadata rule assigns the defined metadata to any matching streams that are subsequently added to the selected namespace. You can edit a metada
This is clunky and could be clearer. The more I try to rewrite this paragraph, the more I think it is too detailed for this section and should be removed.

2021-01-17 20:21 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +The Visualization Trend feature converts data from one or more streams into graphical representations of data values collected over a custom-defined time period. Trend enables you to select one or mo
Collapsed sub heading; implemented edits.

2021-01-17 20:25 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +The example above shows stream data for two streams over a selected period of several days.
Done.

2021-01-17 20:33 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides capabilities that allow you to group and organize operational PI, IoT, and OCS data. By arranging data into forms that can be consumed by third party data science applications, data scie
Done.

2021-01-17 20:38 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Grouping and organization methods
Eliminated and incremented sub headings up.

2021-01-17 21:08 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +  Metadata rules enable users to assign metadata to selected parts of defined stream name patterns.
Fixed bullets and revised as follows:
"Users select a stream name to use as a name pattern, and assign metadata to selected stream name parts, such as a plant location or device category. The resulting stream name pattern with assigned metadata parts defines a metadata rule.  The metadata rule assigns the defined metadata to all streams in a given namespace that match the stream name pattern."

2021-01-17 21:15 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +  Data views facilitate the ordering, indexing, and organization of data from multiple streams.
Done.

2021-01-17 21:19 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +Metadata rules enable users to assign metadata to specific stream name parts, such as a plant location or device category.  A metadata rule assigns metadata defined in the rule to all streams in a gi
Revised as follows:
"Users select a stream name to use as a name pattern, and assign metadata to selected stream name parts, such as a plant location or device category. The resulting stream name pattern with assigned metadata parts defines a metadata rule. The metadata rule assigns the defined metadata to all streams in a given namespace that match the stream name pattern."

2021-01-17 21:30 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +The diagram above shows three data streams for turbines named GEO1 and GEO2.
I backed off a good bit of detail in the section.  This diagram I think is a necessary evil, as metadata rules are a difficult concept and this is about as concisely as it can be explained.

2021-01-17 21:31 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +1.	The color-coded data streams show the specific data each stream is tracking, detailed in the Stream Metadata column.
Done.

2021-01-17 21:35 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	The basic description of the stream data is encoded in the stream name. For example, looking at the first stream in the table, the metadata rule takes what might have been meaningless to a user, *
Revised as follows:

"The basic description of the stream data is encoded in the stream name, but it can be difficult to understand. Use metadata rules to decode this information. For example, the metadata rule translates the stream, GEO1_P.ACT_PV, to GEO1, *Turbine*, and ACT_PV, *Active Power*."

2021-01-17 21:38 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +In addition to being applied to any existing streams, a metadata rule assigns the defined metadata to any matching streams that are subsequently added to the selected namespace. You can edit a metada
It is a point of behavior that should be pointed out.  Revised as follows:

"A metadata rule assigns the defined metadata to any matching streams in the selected namespace, as well as matching streams that are subsequently added to the namespace."

2021-01-17 21:39 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +Data views serve as a bridge between raw OCS data and data science applications. Users can use an API to programmatically align and interpolate data in data views for the purpose of doing advanced an
Done.

2021-01-17 21:41 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +2.	A user creates a data view in OCS based on streams containing the specified metadata, selects specific data elements from the streams, and orders and indexes them as needed.
Done.

2021-01-17 21:42 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +Data views allow you to arrange data fields in a way that they can be consumed by a third-party data science application.
Done.

2021-01-17 21:51 UTC, osimarkrogers commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS visualization tools provide multiple options for viewing selected OCS stream data.
Collapsed sub heading; implemented edits.

2021-01-19 13:34 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +OSIsoft Cloud Services (OCS) consists of several different areas of core functionality: Tenant management, data collection, data organization, and data analysis. The following sections discuss each i
Resolved.

2021-01-19 13:52 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The flow of this document is modeled after the steps that you take to configure OCS to collect data from various sources and organize it for analysis within the platform or third-party data science a
Original sentence: The flow of this document is modeled after the steps that you take to configure OCS to collect data from various sources and organize it for analysis within the platform or third-party data science applications.

I am going to remove it and we can discuss it when we meet today. It feels unnecessary upon further review and doesn't really match what we do in other docs.

2021-01-19 13:58 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The type of data, the location of that data, and the way that a particular source sends data all affect how you can collect that data in OCS. You can choose the data collection technology that best m
Resolved.

2021-01-19 13:59 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +Refer to [OMF Message Format](https://omf-docs.osisoft.com/) for additional information about the OMF specification.
This one was an ask from one of the technical SMEs. Leaving the link here.

2021-01-19 14:01 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> + OCS can collect data from EDS via the OSIsoft Message Format (OMF). Edge Data Store currently includes two built-in protocol adapter components, Modbus and OPC UA, and a storage component that also
This is a holdover from an earlier draft. Removed the line that mentions the information above for clarity.

2021-01-19 14:03 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The Edge Data Store (EDS) is a software component similar to a PI Adapter. It enables you to store data from a device locally and make the data available for local querying. This is useful for displa
Resolved.

2021-01-19 14:16 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The OCS programmatic REST API reads and writes data. It supports JSON format and platform-independent data and retrieval.
Awaiting Architecture feedback. I will update shortly.

2021-01-19 14:21 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +PI Adapters are software components that collect sequential data from edge data sources and send it to OCS or PI Server or both. Use PI Adapters for collecting data from standard systems and protocol
Following up with SME for additional clarification.

2021-01-19 14:31 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +Streams organize data brought from another system into OCS. To define a stream, you must first define a type, which specifies the structure of the data you want to stream into an OCS namespace. Every
This is the language we got from the SME. I'm going to leave it as is.

2021-01-19 14:32 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +You can also use tags to assign information to a stream. A tag is a string value. For example, a tag might identify a region.
I would be reluctant to change this without confirming with reviewers.

2021-01-19 14:37 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +For example, a process engineer and a maintenance technician, might want to see different data from the same stream. Because you cannot change the shape of data belonging to a stream, a stream view a
Reworded, mostly using Angela's suggestion.

2021-01-19 14:38 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +Stream views can perform additional functions, such as convert units of measure and change names so the terminology that is displayed is more appropriate for a particular persona.
done

2021-01-19 14:44 UTC, dwicinas-osisoft commented on Content_Portal/Overview/what-does-ocs-do.md
> +To create a stream view, you create a target type that defines the properties to be made available. Then you map the properties in one or more source types to the target type. The source types and th
done

2021-01-19 15:01 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +OCS provides many configuration and control options that allow administrators to customize interactions with the platform based on organizational requirements. Administrators can create users and cli
Tenant is defined in the next section as a term. Replaced entity with users and clients. RESOLVED.

2021-01-19 15:05 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +Using access control lists (ACLs), administrators can also limit permissions to a resource. Generally, only administrators should have access to tenant management features. Administrators can perform
Reworked: OCS can be customized based on your organization's requirements and needs. Considered RESOLVED

2021-01-19 15:23 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +The concept of identity is the key to how OCS limits access to services and resources available to an entity. An entity’s identity allows OCS to know how much access to grant to that entity. OCS iden
Upon further clarification, its not right either. 
Identity is what can be verified/authenticated only.
RESOLVED as: Identity is the authentication factor of a user or client requesting access to OCS. Identities can be verified.

2021-01-19 15:24 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +After defining tenants, setting permissions and access levels for users, and creating clients for programmatic access, you can begin to configure OCS for data collection. Data collection allows you t
Angela suggests big changes: either removing or stripping down the entire Tenant Management section. We can discuss...

2021-01-19 15:41 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authentication
Seems a bit of a large change at this stage. Team to discuss...

2021-01-19 15:48 UTC, digitaljoshua commented on Content_Portal/Overview/what-does-ocs-do.md
> +### Authorization
we decided to remove the numbered process steps and keep the section basic with a simple definition.

2021-01-19 16:31 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +PI Adapters are software components that collect sequential data from edge data sources and send it to OCS or PI Server or both. Use PI Adapters for collecting data from standard systems and protocol
Caught up with Tina and removed "edge" from the sentence.

2021-01-19 18:56 UTC, osisoft-ezrinsky commented on Content_Portal/Overview/what-does-ocs-do.md
> +The OCS programmatic REST API reads and writes data. It supports JSON format and platform-independent data and retrieval.
Resolved.

2021-02-10 19:19 UTC, merged