Update OMF_Ingress_Specification.md
osisoft/OCS-Docs pull request #334
Opened 2021-01-21 15:20 UTC by osimarkrogers

Updating OMF Ingress specs per OMF versions (holding until OMF v1.2 released)

2021-01-21 23:19 UTC, osisoft-izinman requested changes

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``enum``: Optional array of name/value pairs used to define an allowed set of values. Classification should not be set when defining an enum type.
To be more precise, the "enum" keyword is specifically used to define an enum type. Most of the time customers will be using type messages to create object types. Creating an enum type is mutually exclusive with most of the keywords above which apply to object types. Rather than mentioning the keyword, consider something like the following:
"OMF 1.2 adds support for enum type messages. Enumeration types are able to be created and then used in object types using the "reftypeid" keyword. For more information, see the OMF docs here: https://omf-docs.osisoft.com/documentation_v12/Types/Enum_Type.html".
RefTypeId is an important new concept in 1.2 and should at least be mentioned here. It exists at the type _property_ level which is probably why it was overlooked here.

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +Data definitions, by OMF version, are interpreted as follows:
Data messages aren't any different in 1.2, so this text probably isn't necessary.

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> -uid: omfIngressSpecification
Was this header intended to be removed?

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``tags``: Not supported. If included, this property is ignored
These two lines should end in periods to match the style of the other keywords

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``properties``: Key-value pairs defining the properties of a type.
"Type" and "properties" both exist in 1.0 as well.

2021-01-21 23:19 UTC, osisoft-izinman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +### OMF 1.1
The "uom" keyword was added in 1.1, see here: https://omf-docs.osisoft.com/documentation_v11/Whats_New.html

2021-01-21 23:48 UTC, osisoft-eklein commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +* ``propertyoverrides``: Optional key-value pairs used to override properties on a type definition.
Should mention that "uom" is the only override currently supported.

2021-01-22 00:14 UTC, osisoft-eklein commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +OMF message types fall into three categories: type, container, and data, which are described below.
Why the change in case style here?  In other documents, these special words have title casing (first letter capitalized).  In the Headers section of this document, words like Tenant and Topic use title casing.  If the general style is to use sentence casing rather than title casing for section titles, the title "Property Types and Formats" below should be converted as well.

2021-01-22 14:21 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``tags``: Not supported. If included, this property is ignored
"tags" and "metadata" are supported in 1.0. Why is it listed here as unsupported? This should be corrected.

2021-01-22 14:23 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``properties``: Key-value pairs defining the properties of a type.
Agreed, "type" and "properties" should be added to the 1.0 section and left out here.

2021-01-22 14:30 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``enum``: Optional array of name/value pairs used to define an allowed set of values. Classification should not be set when defining an enum type.
We cannot forget "flags" either. Perhaps Isaac's suggested wording could be updated to say " adds support for `enum` and `flags` type messages. These types are able to be created...".

2021-01-22 14:33 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +Data definitions, by OMF version, are interpreted as follows:
This isn't entirely true from the spec perspective, but true in terms of what OCS handles. We will need this section as soon as we start supporting static types and links.

2021-01-22 14:36 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
>  * ``containerid``: Stream Id for the associated Sds Stream.
"typeversion" is only defined in the 1.0 and 1.1 spec. It is unsupported in those versions in OCS but has been removed from the spec altogether in version 1.2.

2021-01-22 15:54 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> -uid: omfIngressSpecification
No! Good catch....not sure how that happened.  Replaced.

2021-01-22 16:13 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
>  Versions 1.0 and 1.1 of the spec are currently supported.
Done.

2021-01-22 16:22 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +OMF message types fall into three categories: type, container, and data, which are described below.
Correct, the standard is sentence case.  The guild has a current effort underway to apply this standard throughout the doc.  I applied to the rest of this topic....normalization of the OCS doc set is forthcoming.

2021-01-22 19:19 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``tags``: Not supported. If included, this property is ignored
Corrected tags and metadata items.

Applied periods to definitions in form of complete sentence - - incomplete sentences should not have a period.

2021-01-22 21:35 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +### OMF 1.1
Captured.

2021-01-22 21:36 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``properties``: Key-value pairs defining the properties of a type.
Resolved per conversation with Chuck.  Removed from type keywords; supported for container.

2021-01-31 20:54 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``enum``: Optional array of name/value pairs used to define an allowed set of values. Classification should not be set when defining an enum type.
Implemented both comments.

2021-01-31 21:01 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +* ``propertyoverrides``: Optional key-value pairs used to override properties on a type definition.
Comment added.

2021-01-31 21:06 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +Data definitions, by OMF version, are interpreted as follows:
Deleted reference to OMF version until there is a distinction.

2021-01-31 21:19 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
>  * ``containerid``: Stream Id for the associated Sds Stream.
Restored OMF version differentiation for data messages to reflect distinction for v1.2.

2021-02-01 15:03 UTC, osisoft-csleasman commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``enum``: Optional array of name/value pairs used to define an allowed set of values. Classification should not be set when defining an enum type.
The spec documentation hasn't been fully updated yet, but there will be both an `enum` and a `flags` keyword. I'm not sure if you want to include that here now or after the spec documentation has been finalized.

2021-02-01 15:14 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +  + ``enum``: Optional array of name/value pairs used to define an allowed set of values. Classification should not be set when defining an enum type.
It's OK to go in here - - this won't be merged until 1.2 is actually released.

2021-02-02 16:51 UTC, osisoft-csleasman approved these changes
There are potential for a few updates when the 1.2 spec is finalized, but those can happen after the spec is complete.

2021-02-02 17:29 UTC, osisoft-eklein commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +      **Note**: A uom keyword for type properties was added with OMF 1.1.
Should have backticks around "uom"

2021-02-02 17:30 UTC, osisoft-eklein commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +Data definitions. by OMF version, are interpreted as follows:
change period to comma

2021-02-02 17:55 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +      **Note**: A uom keyword for type properties was added with OMF 1.1.
Added backticks.

2021-02-02 17:57 UTC, osimarkrogers commented on Content_Portal/Documentation/DataIngress/OMF_Ingress_Specification.md
> +Data definitions. by OMF version, are interpreted as follows:
Good catch - - Done.

2021-02-02 17:58 UTC, osisoft-izinman approved these changes

2021-02-02 18:27 UTC, osisoft-eklein approved these changes

2021-11-02 01:13 UTC, osisoft-mbishop commented
Closing in favor of https://github.com/osisoft/OCS-Docs/pull/743.

2021-11-02 01:13 UTC, closed without merging