Remove First in {FirstKey} {FirstStreamReferenceName}
osisoft/OCS-Docs pull request #337
Opened 2021-01-25 17:01 UTC by sturnberg

Changing {FirstKey} to {Key} and {FirstStreamReferenceName} to {StreamReferenceName}.

2021-01-27 16:14 UTC, osimarkrogers requested changes

2021-01-27 16:14 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](xref:sdsReadingDataApi#get-sum
I think "calculated summaries" works better as "summary calculations". Also, either form is plural, so should be "Summary calculations/Calculated summaries are defined...."
One more item, I believe "...summary types enumerated in [SdsSummaryType]..." should be "...the [SdsSummaryType]..." as it is referring to the SDS object.

2021-01-27 16:14 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +In the data view a data field defines the type of summary with the SummaryType property as [SdsSummaryType](xref:sdsReadingDataApi#get-summaries#get-summaries). Another property, SummaryDirection, al
"summary's direction" should be "direction of the summary"

2021-01-28 15:46 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +Data views can be configured to show calculated summaries for streams and assets.  �Calculated summaries� is defined as the summary types enumerated in [SdsSummaryType](xref:sdsReadingDataApi#get-sum
Made the changes and also fixed a bad link.

2021-01-28 15:47 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DefineaDataView/Summaries.md
> +In the data view a data field defines the type of summary with the SummaryType property as [SdsSummaryType](xref:sdsReadingDataApi#get-summaries#get-summaries). Another property, SummaryDirection, al
Made the change and fixed another bad link.

2021-02-02 15:21 UTC, osimarkrogers approved these changes

2021-02-02 18:23 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Sets.md
> +- `{Key}` - the value of the first of the `"Keys"` specified on the field
Yes, the definition is unchanged. "First" was removed to shorten the parameter but it's still the first key.

2021-02-02 18:25 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Field_Sets.md
> +- `{Key}` - the value of the first of the `"Keys"` specified on the field
All good - - I've already approved as well.

2021-02-03 14:17 UTC, merged