Update field type eligibility
osisoft/OCS-Docs pull request #338
Opened 2021-01-25 20:29 UTC by jamesbperry

Update and clarify the documentation on which data item field types are considered eligible.

Primary change: TimeSpan and NullableTimeSpan are now considered ineligible.

2021-01-25 20:37 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* The corresponding SDS property type is
do we want to specific point out nested properties?

2021-01-27 14:51 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* The corresponding SDS property type is
I changed "nested" to "Complex (e.g. Object)" thinking that was clearer. What's your preference?

2021-01-27 15:01 UTC, d-ng commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* The corresponding SDS property type is
I looked at SDS doc and can't figure out what term they use specifically. I'll let @osimarkrogers comment on this.

2021-01-27 15:05 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* The corresponding SDS property type is
Perhaps "A structure (e.g. Object)" would fit the pattern of "A collection / A timespan"

2021-02-01 21:48 UTC, osimarkrogers requested changes

2021-02-01 21:48 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +* The corresponding SDS property type is
I recommend keeping both "nested" and "complex". While the distinction isn't really clear in the SDS doc, they are referred to separately, and do appear to be different.  I'd replace the three items below with:

*  Complex (e.g. enumerated types)
*  Nested
*  A collection (e.g. array)
*  A timespan (TimeSpan or NullableTimeSpan)

2021-02-02 15:01 UTC, osimarkrogers requested changes

2021-02-02 15:01 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +  * Compound.
Change to "...or is a compound index"

2021-02-03 13:50 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +  * Compound.
I think we've lost the distinction between the (overall) stream's type, and the (immediately-corresponding) stream property's type.

That distinction is especially important in the world of assets. One asset can refer to multiple streams. Each stream can be of an eligible index type (or not).

How about:
---
A data item field is ineligible if its index is not appropriate for the data view, or if the field has an SdsTypeCode that may not be included in data views.

Examples of ineligible index:
- The index is compound (multiple properties) 
- The index property's SdsTypeCode differs from the IndexTypeCode of the data view

Examples of ineligible field types:
- SdsTypeCode.Object (nested type)
- SdsTypeCode.Array (collection type)
- SdsTypeCode.TimeSpan (time spans are currently unsupported)

2021-02-03 17:11 UTC, osimarkrogers approved these changes

2021-02-03 17:17 UTC, d-ng approved these changes

2021-02-03 17:28 UTC, jamesbperry commented on Content_Portal/Documentation/DataViews/DefineaDataView/Data_Items_and_Groups.md
> +  * Compound.
Change applied per email conversation

2021-02-03 17:29 UTC, merged