Special characters in search strings
osisoft/OCS-Docs pull request #365
Opened 2021-02-25 19:48 UTC by lasato-OSI

Please review the changes in asset-search-api.md

Thank you,
Laureen

2021-02-25 21:53 UTC, dpatel11 requested changes

2021-02-25 21:53 UTC, dpatel11 commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +| Search String                          | Query String                               |
"Search String" should be "Example Field Value"

2021-02-25 21:53 UTC, dpatel11 commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +| Electric Vehicle (EV) Charging Station | Electric Vehicle \\(EV\\) Charging Station |
Remove this example because most of the documents that are tokenized would remove the parenthesis since it is surrounded by whitespace. It would be tokenized as "electric" "vehicle" "ev" "charging" and "station", removing the parenthesis around "EV".

2021-02-26 02:16 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +| Search String                          | Query String                               |
Done.

2021-02-26 02:16 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/asset-search-api.md
> +| Electric Vehicle (EV) Charging Station | Electric Vehicle \\(EV\\) Charging Station |
Done

2021-02-26 17:04 UTC, btandersen approved these changes

2021-02-26 17:08 UTC, dpatel11 approved these changes

2021-02-26 17:09 UTC, btander approved these changes

2021-03-01 18:40 UTC, merged