Create data-views.md
osisoft/OCS-Docs pull request #373
Opened 2021-03-02 02:41 UTC by osimarkrogers

2021-03-02 18:57 UTC, afloresOSI requested changes
See inline suggestions.

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +Data views are subsets of data from one or more streams. You create a data view by defining the target namespace, the source stream or streams, the desired data fields, time period, and interpolation
I wouldn't use the word "desired". 
```suggestion
Data views are subsets of data from one or more streams. You create a data view by defining the target namespace, then specifying the source stream or streams, the data fields, time period, and interpolation interval. 
```

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +1. In the **Data Views** pane of the OCS Portal, click **Add Data View8*.
```suggestion
1. In the **Data Views** pane of the OCS Portal, click **Add Data View**.
```

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +To create a new data view, complete the following:
```suggestion
To create a new data view, complete the following steps:
```

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +## Configure a data view
Why is this a separate section of steps? It seems to be a heading in the middle of a procedure. There are no instructions for getting to the Index Configuration pane outside of performing the previous procedure. Would they ever be performed separately?
There is no introduction sentence for the steps.

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +1. In the **Index Configuration** pane, select the date and time for the **Start Index** and **End Index** to specify the time period of the data to be included in the data view.
```suggestion
1. In the **Index Configuration** pane, select the date and time for the **Start Index** and **End Index** to specify the time period of the data to include in the data view.
```

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +2. Enter a value in the **Time Interval** field to specify the time interval by which to display data. The **Time Interval** field provides entry spaces for Days, Hours, Minutes, and Seconds.
This is a different structure than the other steps.
```suggestion
2. In the **Time Interval** field, specify the time interval by which to display data. The **Time Interval** field provides entry spaces for Days, Hours, Minutes, and Seconds.
```

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +5. In the **Field Management** pane, use the Up and Down Arrows to move selected data fields up or down in the display, and click **Apply**.
I am not sure what the standard for the "up and down arrows" is. Would inline images be possible?

2021-03-02 18:57 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +4. In the **Field Management** pane, click **+ Add** to select available data fields from the query results to include in the data view. Select the data fields you want to add in the **Add Data Field
General rule is not to include extra characters in button names **Add** instead of **+ Add**.
```suggestion
4. In the **Field Management** pane, click **Add**. Then in the **Add Data Fields** window, select the data fields from the query results to include in the data view and click **Add**.
```

2021-03-02 19:15 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +Data views are subsets of data from one or more streams. You create a data view by defining the target namespace, the source stream or streams, the desired data fields, time period, and interpolation
Done.

2021-03-02 19:16 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +1. In the **Data Views** pane of the OCS Portal, click **Add Data View8*.
Good catch - - fixed.

2021-03-02 19:22 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +## Configure a data view
Yes - - I was thinking of this as separate because you can also select a Data view and click "Edit" and get the Configuration page too, but the fact is that you cannot create one from scratch without having to do the configuration steps. So I'll combine them.

2021-03-10 17:34 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +
Please start all procedures by telling the user how to get to the page from the OCS menu.

1. Click the menu icon and click Data Views (under Analytics).

2021-03-10 18:11 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +11. In the **Field Management** pane, click **+ Add** to select available data fields from the query results to include in the data view. Select the data fields you want to add in the **Add Data Fiel
```suggestion
11. In the **Field Management** pane, click **Add** to select available data fields from the query results to include in the data view. Select the data fields you want to add in the **Add Data Fields** dialog and click **Add**.
```
In an earlier step, you tell them to click Add Data View, and you omit the + sign there. I would suggest leaving it off here as well.

2021-03-15 13:23 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +
Done.

2021-03-15 13:45 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +## Configure a data view
Done.

2021-03-15 13:46 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +1. In the **Index Configuration** pane, select the date and time for the **Start Index** and **End Index** to specify the time period of the data to be included in the data view.
Done.

2021-03-15 13:48 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +2. Enter a value in the **Time Interval** field to specify the time interval by which to display data. The **Time Interval** field provides entry spaces for Days, Hours, Minutes, and Seconds.
Done.

2021-03-15 13:51 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +4. In the **Field Management** pane, click **+ Add** to select available data fields from the query results to include in the data view. Select the data fields you want to add in the **Add Data Field
Done.

2021-03-15 14:32 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +5. In the **Field Management** pane, use the Up and Down Arrows to move selected data fields up or down in the display, and click **Apply**.
I tried inline images and got them to work partially - - they're inline (no break), but they're huge, and don't respond to my resizing the source image.  Sticking with "Up and Down Arrows" for now, and will bring up how to scale images at Writer's Inquisition.

2021-03-15 21:46 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/data-views/data-views.md
> +   **Note**: Assets are available for use through specific licensing only. If you are interested in using Assets, contact your account team for more details.
```suggestion
   **Note**: If assets does not appear as a choice, it means you are not licensed for this feature. If you are interested in using assets, contact your account team for more details. 
```

2021-03-16 17:51 UTC, lasato-OSI approved these changes

2021-03-18 15:26 UTC, merged