Create metadata-rules.md
osisoft/OCS-Docs pull request #374
Opened 2021-03-02 21:51 UTC by osimarkrogers

2021-03-02 22:27 UTC, lasato-OSI requested changes
Hi Mark,

This is a repeat of my comment in PR #372.

The procedure needs to be cleaned up. I wasn't clear if Angela reviewed the procedure in PR #372. If not, you may want to start by asking her to do a review. If it's unclear what needs to be done, another alternative is to check with Joyce and see if she can do an edit. 
When you're done, please add me as a reviewer on your PR.

Thanks,
Laureen

2021-03-04 21:51 UTC, joyceseng commented
Hi Mark
I made direct edits to the markdown file in your branch, and I added some comments.
The main things I noticed were that:
There should be only one action in each step.
Break out dense info to a section after the procedure
Use dropdown list or just list, not droplist
The description for the Metadata type called Metadata was rather confusing - can you please tidy it up.

Thanks! /Joyce

2021-03-04 22:55 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +  11.1 To display the raw stream data for the specified metadata key, select **Copy Values** under **Mapping Type**.
This is not correct markdown notation. I don't know if markdown allows you to create substeps.
In the output,

2021-03-04 23:00 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +  11.1 To display the raw stream data for the specified metadata key, select **Copy Values** under **Mapping Type**.
I'm breaking these steps down now - - they are pretty dense.  I think options are either to be bulleted or lettered, but I'll check.

2021-03-10 18:31 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +1. Click **Sequential Data Store** under **Data Management** in the OCS Portal.
```suggestion
1. Click the menu icon in the OCS portal, and click **Sequential Data Store** under **Data Management**. 
```

2021-03-10 18:32 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +6. In the **Metadata Management** page, choose the namespace in which the model stream resides, and the metadata rule is to be created, from the **Namespace** dropdown list.
```suggestion
6. In the **Metadata Management** page, choose the namespace in which the model stream resides and where the metadata rule is to be created, from the **Namespace** drop-down list.
```

2021-03-10 18:34 UTC, lasato-OSI submitted a review, later dismissed
Mark,
 Please change "dropdown list" to "drop-down list" throughout.

2021-03-10 21:52 UTC, joyceseng commented
Hi Mark
I saw a few typos - I recommend reading a topic back after you update it. 

- I saw both "dropdown list" and "drop-down list" - they should all be "dropdown list".
- I saw at least once instance of "steam" when "stream" was intended.

Otherwise, it looks good. With those items fixed, I'm fine with it going ahead, if Laureen is also.
Thanks! /Joyce

2021-03-10 22:02 UTC, osimarkrogers commented
Hi Joyce,

Unfortunately, I saw those right after creating the pull request…. Anyway, I’ll go back through.  Thank you!

From: Joyce Simmonds ***@***.***>
Sent: Wednesday, March 10, 2021 4:52 PM
To: osisoft/OCS-Docs ***@***.***>
Cc: Mark Rogers ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [osisoft/OCS-Docs] Create metadata-rules.md (#374)

Caution: This email came from outside the company.
________________________________

Hi Mark
I saw a few typos - I recommend reading a topic back after you update it.

  *   I saw both "dropdown list" and "drop-down list" - they should all be "dropdown list".
  *   I saw at least once instance of "steam" when "stream" was intended.

Otherwise, it looks good. With those items fixed, I'm fine with it going ahead, if Laureen is also.
Thanks! /Joyce

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_osisoft_OCS-2DDocs_pull_374-23issuecomment-2D796183234&d=DwMCaQ&c=rxxrGm2iek7pTJSSe1mAiw&r=ytSRDgue_YfNLBKz6V47TvXJLRCxu_5GDGHwitLtpNg&m=-Pw8Sl2jTW5Nlf6HVC_g7h1bAdeOtajsMNdNjP4De-Y&s=VE6rfFLpeHTIe796FZtnBMDwoMPIYGtsS5xrKXUAMGQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AJY7R4H2I5FFNMZOR6RCDY3TC7LYZANCNFSM4YPZTJNQ&d=DwMCaQ&c=rxxrGm2iek7pTJSSe1mAiw&r=ytSRDgue_YfNLBKz6V47TvXJLRCxu_5GDGHwitLtpNg&m=-Pw8Sl2jTW5Nlf6HVC_g7h1bAdeOtajsMNdNjP4De-Y&s=XNzVZaH9gA4jzL0EjOCMZIjbhnK4wmS6xfPnO2qzPAc&e=>.

2021-03-10 22:13 UTC, joyceseng commented
Thanks, Mark! Not sure if you noticed, but I had my own typo in my original comment. I edited the comment, but just to make sure:
•	 - they should all be "drop-down list".
I checked with Rainier to make sure.

2021-03-12 17:32 UTC, osimarkrogers commented
> Mark,
> Please change "dropdown list" to "drop-down list" throughout.

Done.

2021-03-12 22:19 UTC, osimarkrogers commented
> Hi Mark
> I saw a few typos - I recommend reading a topic back after you update it.
> 
> * I saw both "dropdown list" and "drop-down list" - they should all be "drop-down list".
> * I saw at least once instance of "steam" when "stream" was intended.
> 
> Otherwise, it looks good. With those items fixed, I'm fine with it going ahead, if Laureen is also.
> Thanks! /Joyce

@lasato-OSI Hi Laureen, I believe all issues have now been addressed, if you'd like to take a final look to approve. (We are currently showing a conflict; I suspect you might know where that's coming from.  If not, let me know and I'll chase it down).
Thanks, Mark

2021-03-16 17:18 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +    **Note**: If you select metadata type **Metadata**, you must also enter a metadata key. A metadata key is the key portion of a key-value pair, typically the type of data provided, such as "Measur
Hi Mark,
Please remove the quotes from the text in this note. When we used DITA tags, we might have used a specific tag to denote this, but since we no longer have these tags, let's leave it unformatted for now. Generally, we avoid using italics. I did verify this with Joyce. She will follow up with Rainier to see if, in the future, we should be formatting it differently. For now, we will leave the text, as is, with no formatting. 

Thanks,
Laureen

2021-03-16 17:43 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/metadata-rules/metadata-rules.md
> +    **Note**: If you select metadata type **Metadata**, you must also enter a metadata key. A metadata key is the key portion of a key-value pair, typically the type of data provided, such as "Measur
Removed.

2021-03-16 17:49 UTC, lasato-OSI approved these changes

2021-03-18 15:26 UTC, merged