Ocs gisellelee configure streams views subbranch
osisoft/OCS-Docs pull request #392
Opened 2021-03-16 21:56 UTC by GiselleLeeOSI

Putting in scaffolding for stream views configuration

2021-03-22 14:03 UTC, GiselleLeeOSI commented
![image](https://user-images.githubusercontent.com/55005036/112002035-ba6bd780-8adc-11eb-8ff1-252f9037a919.png)
Worrysome, UI updated but not the intotab

2021-03-23 22:05 UTC, GiselleLeeOSI commented
1. Adding reviewers for 
 - Content knowledge (@osimarkrogers , @osisoft-ezrinsky , @dwicinas-osisoft )
 - Structure (@lasato-OSI ): as discussed, created the topic but haven't added to the toc yet
 - Consistency (@joyceseng)

2021-03-23 22:16 UTC, GiselleLeeOSI commented
Sorry guys, I notice there are a few files that shouldn't be part of this PR. Let me close this one out and reopen a new one. Apologies.

2021-03-23 22:16 UTC, closed without merging

2021-03-23 22:33 UTC, osimarkrogers requested changes

2021-03-23 22:33 UTC, osimarkrogers commented on Content_Portal/Documentation/SequentialDataStore/SDS_Views.md
> +Stream views provide flexibility in the use of types and allow you to expose data as a different type. While you cannot actually change the properties of types themselves, the stream views feature en
Recommend: "Stream views provide flexibility in the use of types and allow you to view stream data as it would be ordered by another type. While you cannot change the properties of types themselves, the stream views feature enables you to create a view of a selected stream as if it were based on a different type. You create a stream view by designating a source and target type, and then defining mappings between the properties of the two types."

2021-03-23 22:33 UTC, osimarkrogers commented on Content_Portal/add-organize-data/configure-stream-views.md
> +
This procedure needs to be re-written.  You do not create new streams as part of the process of creating a stream view.  Stream views are designed to be applied to existing streams....if you were creating a new stream, you would simply base it on the type you wanted in the first place. There would be no need to view it through a stream view - - the purpose of a stream view is to enable you to see the archived data of a stream through the lens of a different type.  The OCS Portal UI Stream Views feature provides a means to create a stream view, assign two types to it, and define mapping between the properties of the two types (source and target).  The Information tab says that to then apply that stream view to an existing stream requires an API call....I am not aware if there is a UI based means of viewing a stream through the stream view.  I can take this on to revise in the upcoming sprint if that helps.

2021-03-24 10:36 UTC, dwicinas-osisoft commented on Content_Portal/Documentation/SequentialDataStore/SDS_Views.md
> +Stream views provide flexibility in the use of types and allow you to expose data as a different type. While you cannot actually change the properties of types themselves, the stream views feature en
Mark's suggested wording sounds good to me.