Ocs mrogers about assets subbranch
osisoft/OCS-Docs pull request #397
Opened 2021-03-20 17:49 UTC by osimarkrogers

About assets content for review

2021-03-22 02:41 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +Assets are objects used to represent physical entities in OCS.  Assets typically represent devices with multiple data streams, although you can create an asset with only one stream if needed.
```suggestion
Assets represent physical entities in OCS.  Typically, they are configured with multiple data streams, although you can also create an asset with a single stream.
```

2021-03-22 02:43 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. You can creat
```suggestion
An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. Assets typically represent devices with multiple streams. However, you can also create assets with a single stream. You can create assets on an ad hoc basis or create them from an asset type, a template for creating similar assets.
```

2021-03-22 02:45 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +When you create assets in OCS, you can use the Asset Explorer in the OCS Portal to visualize selected data streams and properties for troubleshooting and analysis of the associated devices or entitie
```suggestion
You can use the asset explorer in the OCS Portal to create assets and visualize selected data streams and properties for troubleshooting and analysis of the associated devices or entities.
```

2021-03-22 13:05 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +When you create assets in OCS, you can use the Asset Explorer in the OCS Portal to visualize selected data streams and properties for troubleshooting and analysis of the associated devices or entitie
Done.

2021-03-22 13:06 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. You can creat
Done.

2021-03-22 13:06 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +Assets are objects used to represent physical entities in OCS.  Assets typically represent devices with multiple data streams, although you can create an asset with only one stream if needed.
Done.

2021-03-23 02:11 UTC, afloresOSI requested changes

2021-03-23 02:11 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +For more information on assets, see [Assets](xref:WhatOCSdoes#assets)
Need a period at the end of the sentence.
```suggestion
For more information, see [Assets](xref:WhatOCSdoes#assets).
```

2021-03-23 02:11 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +You can create assets on an ad hoc basis or create them from an asset type, a template for creating similar assets.
Combine with the sentence in the next paragraph.
```suggestion
Use the asset explorer in the OCS Portal to create assets and visualize selected data streams and properties for troubleshooting and analysis of the associated devices. You can create assets on an ad hoc basis or create them from an asset type, which acts as a template for creating similar assets.
```

2021-03-23 02:11 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. Assets typica
```suggestion
An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. Assets typically represent devices with multiple data streams; however, you can create an asset with only one stream if needed. 
```
what is an entity? or at least an example of one? "... or entity, such as a ???."

2021-03-23 02:11 UTC, afloresOSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
>  # About assets
We had a standard for the CMS that we would never begin a topic with "About". I realize that the current OCS help has a bunch of topics that start in this manor, but it is going to make it difficult to search and is unnecessary.

2021-03-23 12:14 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
>  # About assets
@lasato-OSI Perhaps we should discuss this at our next OCS Writers meeting.

2021-03-23 12:17 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +An asset is a container for data streams associated with a particular device or entity. When you create an asset, you scope it to a namespace and a set of streams within that namespace. Assets typica
I think "object" works better.

2021-03-23 12:18 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +For more information on assets, see [Assets](xref:WhatOCSdoes#assets)
Good catch.  Done.

2021-03-23 12:20 UTC, osimarkrogers commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +You can create assets on an ad hoc basis or create them from an asset type, a template for creating similar assets.
Done.

2021-03-23 22:21 UTC, lasato-OSI commented on Content_Portal/add-organize-data/attach-meaning/assets/about-assets.md
> +An asset is a container for data streams associated with a particular device or object. When you create an asset, you scope it to a namespace and a set of streams within that namespace. Assets typica
```suggestion
An asset is a container for multiple data streams. When you create an asset, you scope it to a namespace and a set of streams within that namespace. 
```
Mark, why don't we remove the mention of device/object. I looked back at Victor's feedback on what you wrote about assets for the overview topic, and he said, "No need to mention "a single device" or "multiple devices". The end users who create these digital twin may or may not possess knowledge of the sensors/IoT devices. The key is that an asset can consists of multiple streams."

2021-03-23 22:35 UTC, lasato-OSI approved these changes
We may need to revisit this later, but it's fine for now. Thanks.

2021-03-23 23:08 UTC, afloresOSI approved these changes

2021-03-24 21:50 UTC, merged