Added First-Page and Next-Page headers in Data Views
osisoft/OCS-Docs pull request #403
Opened 2021-03-22 14:08 UTC by sturnberg

Added First-Page and Next-Page headers in Data Views. 
https://dev.azure.com/osieng/engineering/_workitems/edit/194243/

2021-03-22 19:03 UTC, osimarkrogers requested changes

2021-03-22 19:03 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start_Get_Data_View_Data.md
> +When paging through data view data via the REST API, hyperlinks to the first page and next page of data are provided in the `Link` header. The first page header is signified by relation type of first
Change to, "You can page through data using the `First-Page` and `Next-Page` headers in applications that do not support the `Link` header."

2021-03-23 20:45 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start_Get_Data_View_Data.md
> +When paging through data view data via the REST API, hyperlinks to the first page and next page of data are provided in the `Link` header. The first page header is signified by relation type of first
Removed changes. This is a quick start so details like these headers is probably not worth mentioning here.

2021-03-23 20:46 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Removed changes to Link.

2021-03-23 20:46 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Removed changes to Link.

2021-03-23 20:46 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Removed changes to Link.

2021-03-23 20:46 UTC, sturnberg commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there are no additional results to be retrieved. |
Removed changes to Link.

2021-03-23 22:06 UTC, osimarkrogers requested changes
Couple minor changes....some "there is additional results" items got changed back. Just need to be "there are".

2021-03-23 22:06 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Should be "....there are no additional results..."

2021-03-23 22:06 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Should be "...there are no additional results..."

2021-03-23 22:06 UTC, osimarkrogers commented on Content_Portal/Documentation/DataViews/DataViewsAPIOverview/Resolved_Data_View_API.md
> +| Link | Hyperlinks to the first page and next page of results as applicable. Absence of the next link indicates that there is no additional results to be retrieved. |
Should be "...there are no additional results..."

2021-03-25 17:50 UTC, osimarkrogers approved these changes

2021-03-25 18:02 UTC, merged