Update assets documentation
osisoft/OCS-Docs pull request #416
Opened 2021-03-29 20:19 UTC by atangOSIsoft

added updates for:
- Additional behavior and rules updates for metadata and references name and id
- Removal of Name from Status

2021-03-30 17:38 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +To support flexibility, on creation and update, the following rules and behaviors are executed for metadata and stream references on a given asset when that asset is from an asset type.
```suggestion
To support flexibility on creation and update, the following rules and behaviors are executed for metadata and stream references on a given asset when that asset is created from an asset type.
```

2021-03-30 17:41 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = Not specified         | Id matches Asset Type Metadata Id | Uses matching Asset Type Metadata Name |
```suggestion
| Id = "Metadata Id"​ and Name = Not specified         | Id matches asset type metadata Id | Uses matching asset type metadata name |
```

2021-03-30 19:44 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = Not specified​ and Name = "Metadata Name"       | Name matches Asset Type Metadata Name | Use matching Asset Type Metadata Id |
```suggestion
| Id = Not specified​ and Name = "Metadata Name"       | Name matches asset type metadata name | Use matching asset type metadata Id |
```
Anthony,  Why do you have "Metadata Name" in quotes? Is this to indicate that this is a parameter? Is Name a parameter?

2021-03-31 17:48 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = Not specified​ and Name = "Metadata Name"       | Name matches Asset Type Metadata Name | Use matching Asset Type Metadata Id |
I think perhaps that was an initial mistake. Thanks for updating.

2021-04-13 16:33 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = Not specified         | Id matches Asset Type Metadata Id | Uses matching Asset Type Metadata Name |
```suggestion
| `Id` = ***Metadata Id***​ and Name = Not specified         | `Id` matches the asset type's Metadata Id | Uses matching asset type Metadata Name |
```

2021-04-13 16:39 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Example                                             | Metadata value on asset type                          |                                              |
```suggestion
| Asset values                                             | Metadata values on the asset type                          |                                              |
```

2021-04-13 16:39 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +
### Examples

2021-04-13 16:47 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = Not specified         | Id matches Asset Type Metadata Id | Uses matching Asset Type Metadata Name |
```suggestion
| Id = "Metadata Id"​ and Name = Not specified         | Id matches the asset type's Metadata Id | Uses the matching asset type's Metadata Name |
```

2021-04-13 16:48 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Id does not match any Asset Type Metadata Id | Id is used as Name |
```suggestion
|                                                     | Id does not match any asset type Metadata Id | Id is used as Name |
```

2021-04-13 16:49 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Name does not match any Asset Type Metadata Name | GUID is generated for Id |
```suggestion
|                                                     | Name does not match any asset type Metadata Name | GUID is generated for Id |
```

2021-04-13 16:50 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = "Metadata Name"       | Only Id or Name (not both) matches Asset Type Metadata Id or Name | Error. |
```suggestion
| Id = "Metadata Id"​ and Name = "Metadata Name"       | Either Id or Name, but not both, match asset type Metadata Id or Name | Error. |
```

2021-04-13 16:51 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +
###Examples

2021-04-13 16:52 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Example                                             | Metadata value on asset type                          |                                              |
```suggestion
| Asset values                                            | Metadata values on the asset type                          |                                              |
```

2021-04-13 16:53 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = Not specified         | Id matches Asset Type Metadata Id | Uses matching Asset Type Metadata Name |
```suggestion
| Id = "Metadata Id"​ and Name = Not specified         | Id matches the asset type's Metadata Id | Uses the matching asset type Metadata Name |
```

2021-04-13 16:53 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Id matches existing Asset Type Metadata Id | Uses existing matching Metadata Name|
```suggestion
|                                                     | Id matches the existing asset type's Metadata Id | Uses the existing matching Metadata Name|
```

2021-04-13 16:54 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Id does not match any Asset Type Metadata Id | Id is used as Name |
```suggestion
|                                                     | Id does not match any asset type Metadata Id | Id is used as Name |
```

2021-04-13 16:54 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = Not specified​ and Name = "Metadata Name"       | Name matches Asset Type Metadata Name | Use matching Asset Type Metadata Id |
```suggestion
| Id = Not specified​ and Name = "Metadata Name"       | Name matches the asset type's Metadata Name | Uses the matching asset type Metadata Id |
```

2021-04-13 16:55 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Name matches existing Asset Type Metadata Name | Use matching existing Asset Type Metadata Id |
```suggestion
|                                                     | Name matches the existing asset type's Metadata Name | Uses the matching existing asset type Metadata Id |
```

2021-04-13 16:55 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Name does not match any Asset Type Metadata Name | GUID is generated for Id |
```suggestion
|                                                     | Name does not match any asset type Metadata Name | GUID is generated for Id |
```

2021-04-13 16:56 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = "Metadata Id"​ and Name = "Metadata Name"       | Only Id or Name (not both) matches Asset Type Metadata Id or Name | Error. |
```suggestion
| Id = "Metadata Id"​ and Name = "Metadata Name"       | Only Id or Name (not both) matches asset type Metadata Id or Name | Error. |
```

2021-04-13 16:57 UTC, lasato-OSI commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Only Id or Name (not both) matches existing Asset Type Metadata Id or Name | The non-matching Id or Name of the existing Metadata is updated |
```suggestion
|                                                     | Only Id or Name (not both) matches existing asset type Metadata Id or Name | The non-matching Id or Name of the existing Metadata is updated |
```

2021-04-13 17:13 UTC, lasato-OSI requested changes
Hi Anthony,
Here are the changes I made:
- I changed _Asset Type_ to _asset type._
- I guess I'm still unclear when it says: Id = "Metadata Id" if that means that the actual value of Id is _Metadata Id_ or if the values of these two parameters are identical. 
-  When it says something like: _Name matches existing asset type Metadata Id_, is _Metadata Id_ referring to specific "parameters"? (sorry, I may not be using the correct term here.) I'm assuming it does, so I left it as _Metadata Id_, not _metadata_ _Id_.
- I changed the heading of the first column from _Examples_ to _Asset values_ which I think is what this column represents. We also need a heading for the third column, something like: How references are resolved? I added a heading, _Examples_, before the table.

I may need to go through the file again and clean it up for consistency.

2021-04-16 21:39 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Example                                             | Metadata value on asset type                          |                                              |
That change looks fine to me.

2021-04-16 21:41 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/assets-api.md
> +| Id = Not specified​ and Name = "Metadata Name"       | Name matches Asset Type Metadata Name | Use matching Asset Type Metadata Id |
Looks good. Thanks

2021-04-16 21:41 UTC, atangOSIsoft commented on Content_Portal/Documentation/Assets/assets-api.md
> +|                                                     | Name matches existing Asset Type Metadata Name | Use matching existing Asset Type Metadata Id |
Looks good. Thanks

2021-04-20 00:06 UTC, merged