Updated external references (parameters.yml and responses.yml) in prep for next sprint's work
osisoft/OCS-Docs pull request #509
Opened 2021-05-21 20:10 UTC by digitaljoshua

Added a few parameters, added a few response codes

2021-05-24 16:29 UTC, GiselleLeeOSI commented on content/developer-guide/dev-guide-introduction.md
> +OSIsoft Cloud Services developer guide. This is what will appear for users when they click to the developer guide.
Hi Josh, this content is no longer valid. See if you can delete this file from your PR. If unsure, talk to me.

2021-05-24 16:32 UTC, GiselleLeeOSI commented on content/external-references/parameters.yaml
>  query:
query is tricky. There are two kinds: the one that is not supported and the other that is. And the unsupported one is already documented later called query-community. So you shouldn't change the description of this one here.

2021-05-24 16:33 UTC, GiselleLeeOSI commented on content/external-references/parameters.yaml
>    type: text/plain
Same for count and  and skip. You should keep the original definitions (these are actively being used). Instead you should create count and skip as they apply to identity and label them count-identity(or count-client) and skip-identity(skip-client) respectively.

2021-05-24 16:35 UTC, GiselleLeeOSI requested changes
1. Please take a look my comments before making changes. 
2. Please find way to uninclude dev-guide-introduction.md from this pr.

2021-05-25 12:13 UTC, digitaljoshua commented on content/developer-guide/dev-guide-introduction.md
> +OSIsoft Cloud Services developer guide. This is what will appear for users when they click to the developer guide.
i deleted this file from the PR (I think).

2021-05-25 12:42 UTC, digitaljoshua commented on content/external-references/parameters.yaml
>  query:
reverted back to original definitions; created new query-identity, count-identity, skip-identity

2021-05-25 12:42 UTC, digitaljoshua commented on content/external-references/parameters.yaml
>    type: text/plain
reverted back to original definitions; created new query-identity, count-identity, skip-identity

2021-05-25 12:48 UTC, digitaljoshua commented
not sure if i made a mess of things. 

1. I removed the file content/developer-guide/dev-guide-introduction.md from this PR (hopefully I didn't remove it from the actual branch- I don't think I did but the messages for Git are a bit ambiguous)
2. Changed the modified definition of query back to its original verbiage. I'm sure there is a quick way of selecting that particular change in this PR and poof...cutting that out of the PR. But I just couldn't find it. So I copy/pasted the definition back to its original verbiage that way.
3. Ditto for definition of count
4. Ditto for definition of skip
5. Added 3 new parameters: query-identity, query-count, query-skip

2021-05-25 15:52 UTC, GiselleLeeOSI commented on content/external-references/parameters.yaml
> +    Max number of roles to return
Between 82 and 96, don't you want to be consistent in your use of Max vs maximum?

2021-05-25 16:45 UTC, digitaljoshua commented on content/external-references/parameters.yaml
> +    Max number of roles to return
i fixed this

2021-05-25 17:14 UTC, merged