Missed PR fixes
osisoft/OCS-Docs pull request #518
Opened 2021-06-03 21:05 UTC by afloresOSI

2021-06-03 21:10 UTC, rmuolic commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/landing-page3.md
> +# View PI system data for transfer
I think it should be "View PI System data for transfer"?

2021-06-03 21:21 UTC, rmuolic approved these changes
Reviewed and also committed a few updates.

2021-06-04 12:30 UTC, VictoriaTouati-AVEVA approved these changes
Reviewed & approved.

2021-06-04 12:44 UTC, VictoriaTouati-AVEVA requested changes
The topic title change to "View PI System data for transfer" should be "Transfer PI System data" because the main point of this procedure is to illustrate how to transfer data to OCS after querying for and selecting the PI points for the transfer. I will change the topic title in the procedure, menu, and landing page on Angela's branch.

2021-06-04 13:06 UTC, VictoriaTouati-AVEVA reviewed
@rmuolic & @afloresOSI: I changed the title "View PI System data for transfer"  to "Transfer PI System data to OCS" to make it technically accurate.

2021-06-04 18:03 UTC, rmuolic commented
@afloresOSI this PR looks okay now to close to merge.

2021-06-04 21:11 UTC, merged