Metrics moved to new template
osisoft/OCS-Docs pull request #522
Opened 2021-06-08 18:52 UTC by ninlar

Use new template for API doc for Metrics
This API doc must be curated manually due to the unique structure of the API.
This PR contains Andrew's changes to bring it inline with the new API documentation.

2021-06-08 19:00 UTC, GiselleLeeOSI requested changes
Looks good with simple suggested fixes

2021-06-08 19:06 UTC, digitaljoshua approved these changes
I agree with Ji Won's feedback. I'll approve so you can merge after resolving her comments.

2021-06-08 19:08 UTC, ninlar commented on content/api-reference/operations/operations-metrics.md
> +Id of the tenant for this metric.
Resolved

2021-06-08 19:08 UTC, ninlar commented on content/api-reference/operations/operations-metrics.md
> +Id of the tenant for this metric.
Resolved

2021-06-08 19:08 UTC, ninlar commented on content/api-reference/operations/operations-metrics.md
> +Id of metric
Resolved

2021-06-08 19:09 UTC, ninlar commented on content/api-reference/operations/operations-metrics.md
>  Id of the namespace for this metric.
Resolved

2021-06-08 19:28 UTC, GiselleLeeOSI approved these changes
Looks good. Let me know if you want this merged.

2021-06-23 21:38 UTC, GiselleLeeOSI commented
Thomas Porter provided the updated file. Merged that one and will use it instead.

2021-06-23 21:38 UTC, closed without merging