Add stored values data route to Data Views documentation
osisoft/OCS-Docs pull request #526
Opened 2021-06-11 15:25 UTC by emonino

2021-06-12 16:05 UTC, osimarkrogers requested changes

2021-06-14 12:50 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +Get interpolated data for the provided index parameters with paging. See [documentation on paging](xref:DataViewsQuickStartGetData#paging) for further information.
Fixed

2021-06-14 12:52 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +Get stored data for the provided index parameters with paging. See [documentation on paging](xref:DataViewsQuickStartGetData#paging) for further information.
Fixed

2021-06-14 12:52 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/preview-data-api.md
> +Get stored data for the provided data view and index parameters with paging. See [documentation on paging](xref:DataViewsQuickStartGetData#paging) for further information.
Fixed

2021-06-14 12:52 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/preview-data-api.md
> +An array of json values. Each json property corresponds to a field mapping. Property names are the field mapping `.Id`s.
Fixed

2021-06-14 12:52 UTC, emonino commented on content/api-reference/data-views/get-data-view-data/quick-start-get-data-view-data.md
> +| Interval | `interval` | `DefaultInterval` | The interval between index values. Only applies for interpolated retrieval mode.
Fixed

2021-06-14 12:52 UTC, emonino commented on content/external-references/dataviews-summaries.yaml
> +    Gets interpolated data for the provided index parameters with paging. See [documentation on paging](https://ocs-docs.osisoft.com/Content_Portal/Documentation/DataViews/GetDataViewData/Quick_Start
Fixed

2021-06-14 12:55 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +| 400 Bad Request           | error | The request could not be understood by the server due to malformed syntax.
Does the lower case even apply for status code responses? We've always used all uppercase and that seems to be the convention elsewhere in the OCS documentation. Here is an example from Assets - https://docs.osisoft.com/bundle/ocs/page/api-reference/assets/assets-api.html.

2021-06-15 14:22 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +| 404 Not Found             | error | The specified data view identifier is not found.
Skipping for now. Will fix if we decide that status codes should be lower case.

2021-06-15 14:22 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +| 500 Internal Server Error | error | An error occurred while processing the request. See the response body for details |
Skipping for now. Will fix if we decide that status codes should be lower case.

2021-06-15 14:22 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/preview-data-api.md
> +| 400 Bad Request           | error | The data view or the query parameters are not valid. See the response body for details. |
Skipping for now. Will fix if we decide that status codes should be lower case.

2021-06-15 14:22 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/preview-data-api.md
> +| 500 Internal Server Error | error | An error occurred while processing the request. See the response body for details |
Skipping for now. Will fix if we decide that status codes should be lower case.

2021-06-15 15:50 UTC, emonino commented on content/api-reference/data-views/data-views-api-overview/data-api.md
> +| 400 Bad Request           | error | The request could not be understood by the server due to malformed syntax.
I fixed the entire data views API documentation to use lower case lettering for the second word in a status code

2021-06-15 21:01 UTC, osimarkrogers approved these changes

2021-06-15 21:01 UTC, merged