Edited assets API files to be consistent with API documentation stand…
osisoft/OCS-Docs pull request #561
Opened 2021-06-26 00:43 UTC by lasato-OSI

…ards.  Cleaned up inconsistent formatting of properties. Added questions for developer to resolve.

2021-06-26 18:02 UTC, digitaljoshua requested changes

2021-06-26 18:02 UTC, digitaljoshua commented on content/api-reference/assets/assets-acl-api.md
> +| 200 OK        | `AccessControlList` | The default access control list of the assets collection or asset type collection. |
technically a noun phrase and not a complete sentence, so recommend removing period.
FYI: later, if your team decides to implement ext references, all this becomes uniform to the definition in the common.yaml as well.

2021-06-26 18:02 UTC, digitaljoshua commented on content/api-reference/assets/assets.md
> +| Id          | String | Required*  | Metadata value identifier.                    |
A noun phrase should not have a period

2021-06-26 18:02 UTC, digitaljoshua commented on content/api-reference/assets/assets.md
> +| Description | String | Optional  | User-provided description.                                   |
A noun phrase should not have a period

2021-06-26 18:02 UTC, digitaljoshua commented on content/api-reference/assets/assets.md
> +| Value       | String | Optional  | String representation of the metadata.                      |
A noun phrase should not have a period

2021-06-26 18:02 UTC, digitaljoshua commented on content/api-reference/assets/assets.md
> +| Description | String | Optional  | Description text.                                            |
A noun phrase should not have a period

2021-06-28 20:13 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +| 200 OK          | `Resolved Asset` | The resolved asset.                                          |
Okay, I will not make this change.

2021-06-28 20:16 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  - `Id` - Id of the matched asset.
```suggestion
- `Id` - Identifier of the matched asset.
```

2021-06-28 20:16 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  - `Id` - Id of the matched asset.
Done

2021-06-28 20:17 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  - `TypeId` - asset type Id of the asset. This is null if the asset does not reference an asset type.
```suggestion
- `TypeId` - asset type identifier of the asset. This is null if the asset does not reference an asset type.
```

2021-06-28 20:18 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  - `TypeId` - asset type Id of the asset. This is null if the asset does not reference an asset type.
Done

2021-06-28 20:19 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  - `Description` - asset description.
This is a list. Because you have list items that require a period, all list items get periods per MS Style Guide.

2021-06-28 20:23 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
> +- `LastModifiedDate` - last modified date of the asset.
This is a list. Because you have list items that require a period, all list items get periods per MS Style Guide.

2021-06-28 20:29 UTC, lasato-OSI commented on content/api-reference/assets/assets-acl-api.md
> +| 200 OK        | `AccessControlList` | The default access control list of the assets collection or asset type collection. |
See Ji Won's comment above.

2021-06-28 20:30 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-type.md
> +Create a new `AssetTypes` object.
Creates.

2021-06-28 20:31 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-type.md
> +Delete an asset type with a specified identifier. An `AssetType` resource cannot be deleted if it is referenced by any assets unless the `deleteAssets` parameter is explicitly set to true.
Deletes

2021-06-28 20:32 UTC, lasato-OSI commented on content/api-reference/assets/assets.md
> +| Id          | String | Required*  | Metadata value identifier.                    |
Per Ji Won, a period is used here because other items in the table require periods.

2021-06-28 20:32 UTC, lasato-OSI commented on content/api-reference/assets/assets.md
> +| Description | String | Optional  | User-provided description.                                   |
Per Ji Won, a period is used here because other items in the table require periods.

2021-06-28 20:32 UTC, lasato-OSI commented on content/api-reference/assets/assets.md
> +| Value       | String | Optional  | String representation of the metadata.                      |
Per Ji Won, a period is used here because other items in the table require periods.

2021-06-28 20:33 UTC, lasato-OSI commented on content/api-reference/assets/assets.md
> +| Description | String | Optional  | Description text.                                            |
```suggestion
| Description | String | Optional  | Description text                                            |
```

2021-06-28 20:33 UTC, lasato-OSI commented on content/api-reference/assets/assets.md
> +| Description | String | Optional  | Description text.                                            |
Done

2021-06-28 20:33 UTC, GiselleLeeOSI commented on content/api-reference/assets/assets-acl-api.md
> +<!-- Should we make "Assets" singular, as in "Asset" to be consistent with other methods? -->
Updates https://docs.osisoft.com/bundle/ocs/page/api-reference/identity/identity-authorization-code-clients.html#get-total-count-authorization-code-clients-from-tenant

2021-06-28 20:38 UTC, lasato-OSI commented on content/api-reference/assets/asset-type.md
> +Create a new asset type with a specified identifier.
"Create" is present tense.

2021-06-28 20:45 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-centric-data-api.md
> +Returns sampled data for referenced SDS streams.
Per Architecture-approved glossary/terminology standard, I thought the standard is to drop SDS prefix before streams: https://dev.azure.com/osieng/engineering/_wiki/wikis/team-content/25162/OCS-internal-glossary?anchor=sequential-data-store-(sds)

2021-06-28 20:49 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-search-api.md
>  The namespace identifier
We don't use definite article in parameter description. https://github.com/osisoft/OCS-Docs/blob/main/content/external-references/common.yaml

The tenant identifier --> Tenant identifier
The namespace identifier --> Namespace identifier
The asset identifier --> Asset identifier

2021-06-28 20:51 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-search-api.md
> +- `Id` - Identifier of the matched asset.
Why is it capital "I" here? You use lowercase after hyphens elsewhere in the list

2021-06-28 20:53 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-status.md
> +| 200 OK           | Asset status list | On successful `POST`, returns the status of multiple assets. |
Anywhere you call out the HTTP request method (`POST`, `GET`), I think you should add request afterward.

2021-06-28 20:54 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-type.md
> +Create a new asset type with a specified identifier.
Create is an imperative. Use creates. You do it elsewhere within your doc. https://docs.osisoft.com/bundle/ocs/page/api-reference/assets/asset-resolved-asset.html#get-resolved-asset

2021-06-28 20:55 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-type.md
> +Create or update an asset type with a specified identifer.
Creates or updates; see how you did it resolved asset api: https://docs.osisoft.com/bundle/ocs/page/api-reference/assets/asset-resolved-asset.html#get-resolved-asset

2021-06-28 20:55 UTC, GiselleLeeOSI commented on content/api-reference/assets/assets-acl-api.md
> +Returns the calling user or client's access rights to the requested asset or asset type.
Here you are using return*s*

2021-06-28 20:55 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
>  The namespace identifier
```suggestion
Namespace identifier
```

2021-06-28 20:56 UTC, GiselleLeeOSI commented on content/api-reference/assets/assets-api.md
>  Create a new asset with a specified `Id`.
Creates to be in line with 92 above.

2021-06-28 20:56 UTC, GiselleLeeOSI commented on content/api-reference/assets/assets-api.md
> +Create or update an asset with a specified `Id`. If the asset already exists, you can specify an `If-Match` property in the HTTP request header to ensure that the asset is modified only if its versio
Creates or updates

2021-06-28 20:56 UTC, GiselleLeeOSI commented on content/api-reference/assets/assets-api.md
> +Delete an asset with a specified `Id`. You can include an `If-Match` property in the HTTP request header to specify the asset version. The asset is deleted only if the version matches.
Deletes

2021-06-28 21:13 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
> +- `Id` - Identifier of the matched asset.
```suggestion
- `Id` - identifier of the matched asset.
```

2021-06-28 21:13 UTC, lasato-OSI commented on content/api-reference/assets/asset-search-api.md
> +- `Id` - Identifier of the matched asset.
Just because

2021-06-28 21:34 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +| 200 OK           | Asset status list | On successful `POST`, returns the status of multiple assets. |
@atangOSIsoft Hi Anthony, Can you please reply?

2021-06-28 23:01 UTC, lasato-OSI commented on content/api-reference/assets/asset-centric-data-api.md
> +Returns sampled data for referenced SDS streams.
```suggestion
Returns sampled data for referenced streams. 
```

2021-06-29 23:16 UTC, atangOSIsoft commented on content/api-reference/assets/asset-status.md
> +| StreamReferenceId   | String                   | Required  | No          | `Id` for the asset's StreamReference property. <!-- Anthony: Should this be StreamReferences? -->The stream reference must
Yeah, it makes more sense to make this StreamReferences.

2021-06-29 23:16 UTC, atangOSIsoft commented on content/api-reference/assets/asset-status.md
> +<!-- Anthony: Would it be correct and clearer to change "SDS stream property value" above to "SDS `StreamPropertyID` value"? -->
What the above is saying is that we want to update the status with respect to the current value of the Sds Stream Property. This shouldn't be the property id.

2021-06-29 23:26 UTC, GiselleLeeOSI commented on content/api-reference/assets/asset-status.md
> +| 200 OK           | Asset status list | On successful `POST`, returns the status of multiple assets. |
No, I meant  to add 'request' in the description: On successful POST request

2021-06-29 23:31 UTC, atangOSIsoft commented on content/api-reference/assets/asset-status.md
> +| 200 OK           | Asset status list | On successful `POST`, returns the status of multiple assets. |
OH! I see, you mean the text, not actually the content. Yeah, I believe it reads better as "On successful `POST` request, returns the status of multiple assets." We can also just assume that the 200 means all good and put the description as "Returns the status of multiple assets." For 207, we can put : "Partial success. Not all assets were able to be resolved. See response body for additional details."

2021-07-02 01:38 UTC, lasato-OSI commented on content/api-reference/assets/asset-centric-data-api.md
> +**Note:** The inputs to this API matches the SDS stream Get samples values data call.
```suggestion
**Note:** The inputs to this API matches the SDS stream Get sampled values data call.  
```

2021-07-02 01:39 UTC, lasato-OSI commented on content/api-reference/assets/asset-centric-data-api.md
> +<!--Anthony, should "Get samples values" be "Get Sampled Values" (https://osisoft-dev.zoominsoftware.io/bundle/ocs/page/api-reference/sequential-data-store/sds-read-data-api.html#get-sampled-values)
done

2021-07-02 01:40 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +Returns the resolved assets.
```suggestion
Returns multiple resolved assets in one call.
```

2021-07-02 01:41 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +<--! Anthony: I think we forgot to add a description here. Please correct and edit, as necessary. thanks -->
done

2021-07-02 01:42 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
>  Requesting resolved assets for assets with the following `Id`s: "Asset1", "Asset2", and "Asset3".
```suggestion
Requesting resolved assets for assets with the following `Id`s: **Asset1**, **Asset2**, and **Asset3**.
```

2021-07-02 01:42 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +<!-- Anthony: I think you put these in quotes to indicate this is a literal value. If i use bold to indicate a literal value, can I take out the quotes, as in: Requesting resolved assets for assets w
done

2021-07-02 01:43 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +| StreamReferenceId   | String                   | Required  | No          | `Id` for the asset's StreamReference property. <!-- Anthony: Should this be StreamReferences? -->The stream reference must
```suggestion
| StreamReferenceId   | String                   | Required  | No          | `Id` for the asset's StreamReferences property. The stream reference must exist before the status mapping can be created. |
```

2021-07-02 01:44 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +| StreamReferenceId   | String                   | Required  | No          | `Id` for the asset's StreamReference property. <!-- Anthony: Should this be StreamReferences? -->The stream reference must
done

2021-07-02 02:24 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +| 207 Multi Status | Multi Status      | On `POST`, returns the status of multiple assets. For error responses, check the multi-status response for the error and cause. |
```suggestion
| 207 Multi Status | Multi Status      | Partial success. Not all assets were able to be resolved. See response body for additional details. |
```

2021-07-02 02:39 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +| 200 OK           | Asset status list | On successful `POST`, returns the status of multiple assets. |
```suggestion
| 200 OK           | Asset status list | Returns the status of multiple assets. |
```

2021-07-02 02:42 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +<!-- Anthony: I think you put these in quotes to indicate this is a literal value. If i use bold to indicate a literal value, can I take out the quotes, as in: Requesting resolved assets for assets w
```suggestion
```

2021-07-02 02:42 UTC, lasato-OSI commented on content/api-reference/assets/asset-resolved-asset.md
> +<--! Anthony: I think we forgot to add a description here. Please correct and edit, as necessary. thanks -->
```suggestion
```

2021-07-02 02:43 UTC, lasato-OSI commented on content/api-reference/assets/asset-centric-data-api.md
> +<!--Anthony, should "Get samples values" be "Get Sampled Values" (https://osisoft-dev.zoominsoftware.io/bundle/ocs/page/api-reference/sequential-data-store/sds-read-data-api.html#get-sampled-values)
```suggestion
```

2021-07-02 02:44 UTC, lasato-OSI commented on content/api-reference/assets/asset-status.md
> +<!-- Anthony: Would it be correct and clearer to change "SDS stream property value" above to "SDS `StreamPropertyID` value"? -->
```suggestion
```

2021-07-02 15:32 UTC, atangOSIsoft approved these changes

2021-07-06 23:53 UTC, merged