Consistency edits
osisoft/OCS-Docs pull request #568
Opened 2021-06-30 17:35 UTC by afloresOSI

2021-07-20 00:19 UTC, rmuolic requested changes
Minor comments on my end.
I noticed comments addressed to the writer to clarify or add additional content. When/how will these comments be addressed?

2021-07-20 00:19 UTC, rmuolic commented on content/add-organize-data/store-data/streams/streams-concept.md
> +<!-- Angela Flores 6/10/21 - The last sentence still has two instances of passive voice. -->
Will the writer update or should we just update now? "will be" to "is".

2021-07-20 00:19 UTC, rmuolic commented on content/add-organize-data/store-data/types/types-best-practices.md
> +- When you create SDS types, the most important thing to be aware of is that types are immutable. Once created, additional properties or information cannot be added and existing properties cannot be
Suggest to not use "thing". 
"When you create SDS types, it is important to be aware that types are immutable..."

2021-07-20 00:19 UTC, rmuolic commented on content/overview/get-started/introduction-portal-interface.md
> +- **Visualization**: Allows you to view data trends and use assets to set up digital twins of real-world physical entities. <!--Angela Flores 6/23/21 - this is the only place in the documentation tha
"digital twins" sounds like an analogous term. I assume it means "simulated copies" or "simulations of real-world physical entities".

2021-07-20 20:17 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/pi-point-change.md
> +To see what types of point coercions are supported in PI Data Archive, please refer to the ["Allowable point type coercions"](https://docs.osisoft.com/bundle/pi-server/page/allowable-point-type-coerc
```suggestion
To see what types of point coercions are supported in PI Data Archive, refer to the ["Allowable point type coercions"](https://docs.osisoft.com/bundle/pi-server/page/allowable-point-type-coercions.html) topic.<!--Angela Flores 6/28/21 should that be "coercions" or "conversions"? -->
```

2021-07-20 20:20 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/pi-point-change.md
> +To see what types of point coercions are supported in PI Data Archive, please refer to the ["Allowable point type coercions"](https://docs.osisoft.com/bundle/pi-server/page/allowable-point-type-coerc
It really is "coercions".

2021-07-20 20:21 UTC, afloresOSI commented on content/developer-guide/identity-dev/dev-guide-preconfigured-roles.md
> +OCS provides includes the following preconfigured roles:
```suggestion
OCS includes the following preconfigured roles:
```

2021-07-20 20:22 UTC, afloresOSI commented on content/developer-guide/identity-dev/dev-guide-preconfigured-roles.md
> +OCS provides includes the following preconfigured roles:
And this is why everyone needs their work doc QA'd.

2021-07-20 20:33 UTC, afloresOSI commented on content/add-organize-data/store-data/streams/streams-concept.md
> +<!-- Angela Flores 6/10/21 - The last sentence still has two instances of passive voice. -->
It is still passive voice, but I can live with it.

2021-07-21 17:12 UTC, rmuolic approved these changes

2021-07-21 21:38 UTC, merged