Jsimmonds get started subbranch
osisoft/OCS-Docs pull request #570
Opened 2021-07-01 16:21 UTC by joyceseng

Hi Angela
I have agreement from my developer, Doug Broad, that this content is ready for Doc QA. Thanks!! /Joyce

2021-07-01 21:26 UTC, afloresOSI requested changes
Joyce, This looks really good. I have a few suggested edits and some formatting changes. Please let me know if you have questions.

2021-07-01 21:26 UTC, afloresOSI commented on content/overview/get-started/gs-stream-views.md
> +Using a stream view on data retrieval affects only the data retrieved, and does not alter the original source data.
Consider combining these opening paragraphs, since three of the four are only one sentence each and they are all related.

2021-07-01 21:26 UTC, afloresOSI commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +You can use stream views to limit these properties or to give them a more meaningful name.
If you want this to appear on a separate line in the output, there needs to be a blank line before it. Otherwise it appears on the same line as the bullet text.
```suggestion
You can use stream views to limit these properties or to give them more meaningful names.
```

2021-07-01 21:26 UTC, afloresOSI commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +OCS provides a graphical interface for setting up stream views, or you can use REST APIs to define stream views programmatically. If you are using the .NET framework, OSIsoft also offers client libra
```suggestion
Use the OCS portal to set up stream views, or use REST APIs to define stream views programmatically. If you are using the .NET framework, OSIsoft also offers client libraries to help you create and use stream views.
```

2021-07-01 21:26 UTC, afloresOSI commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +For information about setting up a stream view, see [Get started with stream views](xref:gsStreamviews).
The "For information" lines appear in the paragraph above in output. If you want them to appear on separate lines, you need to add a blank line before each one.

2021-07-01 21:26 UTC, afloresOSI commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +* When you use a stream view, use caution when not all properties in the target type exist in the source type. Properties that are not mapped return their default value in the target type. For exampl
```suggestion
* When you use a stream view, use caution when not all properties in the target type exist in the source type. Properties that are not mapped return their default value in the target type. For example, if the target type contains a property of data type `double` that is not mapped, data transformation gives that property a value of `0`.
```

2021-07-01 21:26 UTC, afloresOSI commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +For example, assume you have a source type with the properties, Timestamp and Pressure. You create a stream view that maps to a type with the properties Timestamp, Pressure, and Temperature. If Tempe
```suggestion
Assume you have a source type with the properties, Timestamp and Pressure. You create a stream view that maps to a type with the properties Timestamp, Pressure, and Temperature. If Temperature is of data type `double`, a value of 0 (zero) is always returned for it, because it cannot be mapped from the source type. 
```
If you want to separate the examples from their bullets, they need a preceding blank line. Otherwise, the carriage return isn't needed.

2021-07-08 16:34 UTC, joyceseng commented on content/add-organize-data/organize-data/stream-views/stream-views-concept.md
> +For information about setting up a stream view, see [Get started with stream views](xref:gsStreamviews).
Thanks! Lines added.

2021-07-08 16:41 UTC, joyceseng commented on content/overview/get-started/gs-stream-views.md
> +Using a stream view on data retrieval affects only the data retrieved, and does not alter the original source data.
I get what you mean. In this case, I prefer the "separateness" as I want each idea to sink in.

2021-07-08 16:42 UTC, joyceseng commented on content/overview/get-started/gs-stream-views.md
> +1. Click the **Namespace** selection button to open the `Select a Namespace` window. In the `Select a Namespace` window, click **MyOCS**.
I removed the screen cap - I don't think it really helps.

2021-07-08 16:47 UTC, joyceseng commented
I believe I addressed all Doc QA corrections/suggestions. Thanks, Angela!

2021-07-08 16:47 UTC, merged