Mrogers data view updates
osisoft/OCS-Docs pull request #586
Opened 2021-07-12 20:06 UTC by osimarkrogers

2021-08-12 14:15 UTC, rmuolic commented
@jamesbperry Hi Brandon, per James Golla's update on the support for non-datetime index types feature being back in for Postcard, I re-added back in the updated content for quick-start-get-data-view-data.md and quick-start-define-a-data-view.md for from your [PR 611](https://github.com/osisoft/OCS-Docs/pull/611/files).

2021-09-09 14:20 UTC, jamesbperry approved these changes

2021-09-24 23:45 UTC, osisoft-mbishop requested changes
From a doc qa perspective, I have a few style guide suggestions, but otherwise ok.

From a peer review perspective, not so much. I know you aren't the original author, but I had a hard time following the step-by-step:

* The doc references labels that don't appear in the UI, which can be confusing.
* Many of the steps lack context for what certain options do. For example, I'm lost on what "Grouping Fields" and "Identifying Fields" options are for.
* Additionally, there are lots of references to different panes and similarly named UI elements, which are easy to get lost in. 

I also think this procedure might benefit being broken into a "mega task": 1. Create a data view, 2. Add queries to data view, 3. Configure queries, etc.

I also think adding some screen caps would be helpful. I know they're difficult to manage, but in this situation, with a combination of unlabled panes or similarly labled fields, they would be helpful.

Sorry for the dings, as I know you aren't the OG author here. I know much of this feedback likely can't be addressed this sprint, but we should think about some rewrites in the future.  Let me know if you want to talk about any of them in person.

2021-09-24 23:45 UTC, osisoft-mbishop commented on content/add-organize-data/organize-data/data-views/data-views.md
> +1. Click the **View in API Console** button to display basic parameters of the data view in the API console.
Again, I think you can omit this step. Viewing the API console doesn't affect user outcome when creating a data view. Information about the API console in relation to data views might be better as a stand-alone task.

```suggestion
```

2021-09-24 23:45 UTC, osisoft-mbishop commented on content/api-reference/data-views/get-data-view-data/quick-start-get-data-view-data.md
> +For `DateTime` indexed data views, index values should use ISO 8601 format and can be in either UTC or local time with an offset specified. Data retrieved using the [Data API](xref:DataViewsDataAPI)
Rewrite this in present tense. Make it active voice as well. Suggestion:

```suggestion
For `DateTime` indexed data views, use the ISO 8601 format  as the index value. Format interval timespan values using the standard timespan format. For example, d.hh:mm:ss.fffffff. Use either UTC or local time with an offset specified. Data retrieved using the [Data API](xref:DataViewsDataAPI) returns in UTC.
```

2021-09-27 18:04 UTC, rmuolic commented on content/add-organize-data/organize-data/data-views/data-views.md
> +   **Note**: You can click the **Add Query** button to create as addtional queries.
```suggestion
1. Select the **Add** button to add additional queries.
```

2021-09-27 18:11 UTC, rmuolic commented on content/add-organize-data/organize-data/data-views/data-views.md
> +   **Note**: You can click the **Add Query** button to create as addtional queries.
```suggestion
1. Select the **Add** button to add additional data fields to the query.
```

2021-10-13 05:55 UTC, closed without merging