254302 mbishop remove refs to nav icon
osisoft/OCS-Docs pull request #681
Opened 2021-09-16 00:37 UTC by osisoft-mbishop

* Updated first steps in procedures for new menu.
* Updated [Introduction to the OCS portal](https://osisoft-dev.zoominsoftware.io/bundle/ocs-254302-mbishop-remove-refs-to-nav-icon/page/overview/get-started/introduction-portal-interface.html) for menu changes.
* Removed extra "Log in" step where applicable.
* Updated procedure numbering when it got out of sequence.

2021-09-16 13:35 UTC, VictoriaTouati-AVEVA approved these changes
The changes look great, thanks for making these updates.

2021-09-16 13:48 UTC, afloresOSI approved these changes

2021-09-17 18:28 UTC, rmuolic requested changes
Minor observation.

2021-09-17 18:28 UTC, rmuolic commented on content/overview/get-started/gs-users.md
> +1. In the left pane, select **Security > Users**.
```suggestion
1. In the left pane, select **Security** > **Users**.
```

2021-09-17 18:34 UTC, rmuolic approved these changes

2021-09-22 21:58 UTC, merged