Pbi 254312 projectile rebranding
osisoft/OCS-Docs pull request #698
Opened 2021-09-27 15:59 UTC by VictoriaTouati-AVEVA

This work was done for the UI rebranding. Screenshots have been updated to reflect the new UI. In several topics, screenshots were removed if not essential. Some of the steps needed minor updating/rewording due to new UI elements. Need someone to verify that the More Options commands exist in Communities since I did not have access to it.

2021-10-01 07:48 UTC, rmuolic requested changes
Minor comments and suggested changes from my review.

2021-10-01 07:48 UTC, rmuolic commented on content/overview/get-started/introduction-portal-interface.md
> +| 4 - User profile icon  | Click to view a menu of the following commands: The currently logged in user, tenant details, resource usage, feedback page, and sign out of the portal. |
```suggestion
| 2 - View Notifications icon | Click to view OCS-generated notifications. | 
| 3 - Question mark icon | Click to access the online documentation. |
| 4 - User profile icon | Click to view a menu of the following commands: The currently logged in user, tenant details, resource usage, feedback page, and sign out of the portal. |
```

2021-10-01 07:48 UTC, rmuolic commented on content/overview/get-started/gs-metadata-rules.md
> +1. In the **Map To** text box, enter **Philadelphia**.
Same here, why enter a particular city name?

2021-10-01 07:48 UTC, rmuolic commented on content/overview/get-started/gs-asset-types.md
>       -  ![Card view](images/card-view.png) &ndash; Card view displays the asset types as a series of tiles
```suggestion
     -  ![Card view](images/card-view.png) &ndash; Card view displays the asset types as a series of tiles.
```

2021-10-01 07:48 UTC, rmuolic commented on content/overview/get-started/gs-asset-types.md
> +     -  ![Table view](images/table-view.png) &ndash; Table view displays the asset types in a table format
```suggestion
     -  ![Table view](images/table-view.png) &ndash; Table view displays the asset types in a table format.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/store-data/types/types-procedure.md
>     - `Name` &ndash; (Optional) User-friendly name. If you do not provide a name, the Id will be assigned as the name.
```suggestion
   - `Id` &ndash; Id for referencing the type
   
   - `Name` &ndash; (Optional) User-friendly name. If you do not provide a name, the Id will be assigned as the name.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  2. On the `Sequential Data Store` page, click **Streams**.
```suggestion

1. On the `Sequential Data Store` page, click **Streams**.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
> +3. Click the **Change Namespace** button in the upper-right toolbar, then select the namespace in which you want to create the stream.
```suggestion

1. Click the **Change Namespace** button in the upper-right toolbar, then select the namespace in which you want to create the stream.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  4. Expand the `Streams` pane if necessary to copy the full name of the stream that will be the basis for your metadata rule.
```suggestion

1. Expand the `Streams` pane if necessary to copy the full name of the stream that will be the basis for your metadata rule.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
> +5. In the left pane, click **Data Management** > **Metadata Management**.
```suggestion

1. In the left pane, click **Data Management** > **Metadata Management**.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  11. For each delimited section of the stream name you select, use the drop-down list to assign a metadata type: Metadata, String Literal, or Wildcard. See the table following this procedure for a des
```suggestion
1. For each delimited section of the stream name you select, use the drop-down list to assign a metadata type: Metadata, String Literal, or Wildcard. See the table following this procedure for a description of these metadata types. 
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  12. After entering all metadata type entries, click **Next**.
```suggestion
1. After entering all metadata type entries, click **Next**.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  13. In the `Define Mappings` page, choose one of the following options:
```suggestion
1. In the `Define Mappings` page, choose one of the following options:
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  14. If you selected **Map Values**, then do the following: In the **Map To** field, enter the label you want displayed for each defined metadata key, and click **Next**.
```suggestion

1. If you selected **Map Values**, then do the following: In the **Map To** field, enter the label you want to display for each defined metadata key, and click **Next**.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
> +15. Optional: Click **Add Mapping** to define a mapping for any other stream name part.
```suggestion

1. Optional: Click **Add Mapping** to define a mapping for any other stream name part.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/metadata-rules/metadata-rules-procedure.md
>  18. Click **Save & Execute**.
```suggestion

1. Click **Next**. All matching streams for the rule are displayed.

1. Enter the metadata rule **Name** and **Description** in the `Preview and Run` page.

1. Click **Save & Execute**.
```

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/assets/create-asset-rule.md
> +   <!-- WRITER'S NOTE: All the screen captures need to be reviewed and probably updated. In particular, the screen captures in this "Step 1: Extract the tokens from the stream" will need to be update
Should there be an updated screen capture here?

2021-10-01 07:48 UTC, rmuolic commented on content/add-organize-data/organize-data/assets/create-asset-rule.md
> +   <!--WRITER'S NOTE: These images were taken with SnagIt and reduced by 50%. The resolution may be too fuzzy and they may have to be enlarged. -->
Should there be an updated screen capture here?

2021-10-01 21:03 UTC, VictoriaTouati-AVEVA commented on content/add-organize-data/organize-data/assets/create-asset-rule.md
> +   <!--WRITER'S NOTE: These images were taken with SnagIt and reduced by 50%. The resolution may be too fuzzy and they may have to be enlarged. -->
Took this graphic out. I think it's ok as is...will check w/writer (AF?) on Monday.

2021-10-01 21:04 UTC, VictoriaTouati-AVEVA commented on content/add-organize-data/organize-data/assets/create-asset-rule.md
> +   <!-- WRITER'S NOTE: All the screen captures need to be reviewed and probably updated. In particular, the screen captures in this "Step 1: Extract the tokens from the stream" will need to be update
I don't think the screen capture is necessary. Will consult w/writer (AF).

2021-10-01 21:06 UTC, VictoriaTouati-AVEVA commented on content/overview/get-started/gs-types.md
> +1. Click the ![More Options button](images/more-options.png) icon, then click **View Type**. <!--VTT, 9/22/21: It appears this step is no longer needed + the View Type command is not on the More Opti
Deleted.

2021-10-01 21:06 UTC, VictoriaTouati-AVEVA commented on content/overview/get-started/gs-metadata-rules.md
> +1. In the **Map To** text box, enter **San Leandro**.
I have no clue. I did not author this topic.

2021-10-01 21:06 UTC, VictoriaTouati-AVEVA commented on content/overview/get-started/gs-metadata-rules.md
> +1. In the **Map To** text box, enter **Philadelphia**.
I have no clue. I did not author this topic.

2021-10-04 17:25 UTC, rmuolic approved these changes

2021-10-04 18:20 UTC, merged