Vtouati pbi 273623 spm edits
osisoft/OCS-Docs pull request #787
Opened 2021-12-08 13:40 UTC by VictoriaTouati-AVEVA

Edits to several PI to OCS topics per SPM's review.

2021-12-09 22:18 UTC, osisoft-mbishop commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/overview-pi-to-ocs/min-sys-reqmnts.md
>  | PI to OCS Agent | <ul><li> Install on a different computer than your PI Server deployment.</li><li>Use a domain account on a machine registered to the same domain.<br>**Note:** Windows Active Direc
Same here:

```suggestion
| PI to OCS Agent | <ul><li> Install on a different computer than your PI Server deployment.</li><li>Use a domain account on a machine registered to the same domain.<br>**Note:** Windows Active Directory (AD) is required.</li></ul> |
```

2021-12-09 22:22 UTC, osisoft-mbishop requested changes
Hi Vicki,

Your changes look good, but I found a couple of issues with the HTML in one of the file's markdown table. I suggested some fixes.

2021-12-10 19:17 UTC, afloresOSI requested changes

2021-12-10 19:17 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/overview-pi-to-ocs/min-sys-reqmnts.md
> +| PI Server | <ul><li>Use PI Data Archive 2017 SP2 and PI AF 2017 R2 or later for full support of PI to OCS features (transfer out of order events)<br><li>Minimum version: PI Data Archive 2016 R2</li
We don't usually use the "strong" tag. Our standard is ** for bold.

2021-12-10 19:17 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/overview-pi-to-ocs/pi-to-ocs-best-practices.md
> +Note: Multiple PI to OCS Agents can connect to and transfer data from the same PI Server if the agents are installed on different machines and assigned to different namespaces within the same tenant.
```suggestion
**Note:** Multiple PI to OCS Agents can connect to and transfer data from the same PI Server if the agents are installed on different machines and assigned to different namespaces within the same tenant.  
```

2021-12-10 19:17 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
>  1. Click **Ok**.
```suggestion
1. Select **Ok**.
```
Microsoft standard is to use "Select" instead of "Click".

2021-12-10 19:17 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
>     **Result:** The transfer is created and the `Transfer` page opens.
```suggestion
   The transfer is created and the `Transfer` page opens.
```

2021-12-10 19:57 UTC, rmuolic commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/overview-pi-to-ocs/min-sys-reqmnts.md
> +| PI Server | <ul><li>Use PI Data Archive 2017 SP2 and PI AF 2017 R2 or later for full support of PI to OCS features (transfer out of order events)<br><li>Minimum version: PI Data Archive 2016 R2</li
Remove "...if you wish..." <-https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/want

2021-12-10 20:11 UTC, rmuolic requested changes
@VictoriaTouati-AVEVA 

In the topic **transfer-data-to-ocs.md**, a few lines should be updated.

Throughout the topic:
1. Change Optional: to (Optional) 
2. Change Click to Select
3. Remove Result:

4. Line 67: NOTE: to Note:

For **min-sys-reqmnts.md**, remove "if you wish".

2021-12-16 19:37 UTC, VictoriaTouati-AVEVA reviewed
All changes applied.

2021-12-16 19:38 UTC, VictoriaTouati-AVEVA reviewed
All reviewers' changes applied.

2021-12-17 16:56 UTC, afloresOSI approved these changes

2021-12-17 17:47 UTC, rmuolic approved these changes

2021-12-22 12:42 UTC, VictoriaTouati-AVEVA reviewed
All edits applied.

2021-12-22 12:43 UTC, merged