Pbi 279543 landing page consistency
osisoft/OCS-Docs pull request #795
Opened 2021-12-14 22:12 UTC by jasnames

2021-12-15 21:10 UTC, afloresOSI requested changes

2021-12-15 21:10 UTC, afloresOSI commented on content/visualize-data/power-bi-connector.md
> +   <!-- Jason Ames 12/14/21 - Something about this final indent breaks this display and puts the table and note in a code box. Maybe this many indent levels aren't supported?-->
@rmuolic Can you take a look at this display issue in the Power BI topic?

2021-12-15 21:21 UTC, afloresOSI commented on content/visualize-data/visualize-data-overview.md
> +<!-- Jason Ames 12/14/21 - This overview says nothing about the Power BI Connector and only addresses Trend, which has it's own landing page already. A more generic intro that actually mentions visua
@rmuolic Do you have updates planned for this?

2021-12-15 21:33 UTC, jasnames commented on content/overview/get-started/gs-clients.md
> +<!--Jason Ames 12/13/21 Since we haven't otherwise listed the names of the client types, I'd prefer to leave the bullets in here even though the links are redundant to the Related Links.-->
done

2021-12-15 23:20 UTC, rmuolic commented on content/visualize-data/visualize-data-overview.md
> +<!-- Jason Ames 12/14/21 - This overview says nothing about the Power BI Connector and only addresses Trend, which has it's own landing page already. A more generic intro that actually mentions visua
> @rmuolic Do you have updates planned for this?

@afloresOSI - Yes, I'm planning on implementing conceptual content in an upcoming sprint, see [PBI 265023](https://dev.azure.com/osieng/engineering/_workitems/edit/265023).

2021-12-16 18:09 UTC, rmuolic commented on content/visualize-data/power-bi-connector.md
> +   <!-- Jason Ames 12/14/21 - Something about this final indent breaks this display and puts the table and note in a code box. Maybe this many indent levels aren't supported?-->
@afloresOSI 
The display looks fine in Zoomin. GitHub just does not display this indent level correctly. 

https://docs.osisoft.com/bundle/ocs/page/visualize-data/power-bi-connector.html

2021-12-16 18:14 UTC, afloresOSI commented on content/visualize-data/power-bi-connector.md
> +   <!-- Jason Ames 12/14/21 - Something about this final indent breaks this display and puts the table and note in a code box. Maybe this many indent levels aren't supported?-->
Really? It is supposed to be in a code block? The last image isn't showing, it is showing the path in repo.

2021-12-16 18:36 UTC, afloresOSI approved these changes

2021-12-16 19:24 UTC, merged