Add gsassetrules
osisoft/OCS-Docs pull request #823
Opened 2022-01-31 20:53 UTC by joyceseng

2022-01-31 21:09 UTC, afloresOSI requested changes

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +- [Asset rules](xref:ccAssetRules)
```suggestion

```
Remove bulleted list.

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +   - `Name` &ndash; **MyData.AssetRule**
Needs blank lines after each bullet.

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +1. Initially, **MyData** should be highlighted. Use the slider to select the `.` character, so that **MyData.** is highlighted.
Needs blank lines between each numbered item.

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +
There is an extra line here.

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +   - Id &ndash; **{Id}**
Need a blank line after each bullet and number.

2022-01-31 21:09 UTC, afloresOSI commented on content/overview/get-started/gs-asset-rules.md
> +1. Use the view selection at upper right to toggle between list and table view of the assets. The **Asset Preview** panel at left shows the rule details and statistics.
Needs a blank line.

2022-01-31 21:12 UTC, joyceseng commented
Are some of these the same changes you requested in the PR I closed?? Just asking for future reference, as I thought I had put them in ☹

From: Angela Flores ***@***.***>
Sent: Monday, January 31, 2022 1:10 PM
To: osisoft/OCS-Docs ***@***.***>
Cc: Joyce Simmonds ***@***.***>; Author ***@***.***>
Subject: Re: [osisoft/OCS-Docs] Add gsassetrules (PR #823)

CAUTION - This message originated outside AVEVA

@afloresOSI requested changes on this pull request.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796064006>:

> +To create a new asset rule, follow the steps in the these procedures.

+

+1. [Create a new asset rule](#create-new-rule-#1): Create a new asset rule.

+

+2. [Extract tokens](#extract-tokens-#2): Assemble token values so you can select the information you want from your streams.

+

+3. [Map tokens](#map-tokens-#3): Map the tokens to values.

+

+4. [Configure assets](#configure assets-#4): Assign tokens values to asset fields.

+

+5. [Preview assets](#preview-assets-#5): Display a preview of the assets that will be created by this rule.

+

+For more information about asset rules, see [Asset rules](xref:ccAssetRules).

+

+

+- [Asset rules](xref:ccAssetRules)
⬇️ Suggested change

-- [Asset rules](xref:ccAssetRules)

Remove bulleted list.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796064240>:

> +- [PI Server counterpart](xref:ccAssetRules#assetrules-pi-server)

+- [Stream views best practices](xref:ccAssetRules#assetrules-bestpractices)

+

+## <a name="gsAssetRules-create-new-rule"></a> Create a new asset rule

+

+Create a new asset rule.

+

+1. In the left pane, select  **Data Management>Asset Rules**.

+

+1. From the **Namespace** dropdown list, ensure the correct namespace is selected.

+

+1. In the toolbar, select **Add a Rule**.

+

+1. In the **Create New Asset Rule** window, enter the following information.

+

+   - `Name` &ndash; **MyData.AssetRule**

Needs blank lines after each bullet.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796064791>:

> +   - `Description` &ndash; Optionally, add a description for this asset rule.

+   - `Asset Type` &ndash; Select the **MyData.PumpType** asset type from the dropdown list.

+

+1. Select **Continue** to proceed to the **Select Stream** window.

+

+1. In the **Enter search query** field, enter the query string **MyData.\*** and select **Search**.

+

+   The window should display the **MyData.NorthAmerica.SLTC.PumpA** and **MyData.NorthAmerica.SLTC.PumpB** streams.

+

+1. Select the **MyData.NorthAmerica.SLTC.PumpA** stream and select **Add**.

+

+## <a name="gsAssetRules-extract-tokens"></a> Extract tokens

+

+Assemble token values so that you can select the information you want to extract from your streams.

+

+1. Initially, **MyData** should be highlighted. Use the slider to select the `.` character, so that **MyData.** is highlighted.

Needs blank lines between each numbered item.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796065441>:

> +1. For the **1. Match:** option, select **the string literal "MyData."**. The asset rule will find only streams begin with this string.

+

+   **Note**:  In this case, the token value is not named and is not used in the asset configuration.

+1. Select **Capture** to move to the next character group. The first matching rule is listed and the next group, **NorthAmerica**, is highlighted.

+1. For the **2. Match:** option, select **letters preceding the delimiter "."**. This allows you to use this as a token in the asset configuration.

+1. In the **and name it:** field, enter **Region**, and select **Capture**. This adds two rules, one for the Region and another for the "." delimiter.

+1. Next, **SLTC** is selected. In this case, we know our naming pattern enforces a 4-letter abbreviation for the site, so in **3. Match:** select **the next 4 letters**. This helps ensure we do not match any streams that we do not expect.

+1. Name this token **Site** and select **Capture**.

+1. Now, **PumpA** is selected. Because we want to distinguish pump streams from other streams, use the slider to select only **Pump**, and select **the next 4 characters of any type**.

+1. Name this token **Equipment** and select **Capture**.

+1. Finally, just **A** is selected. Use the option **letters until the end of stream name**, and name this token **Id**.

+1. Select **Capture**.

+

+**Note**: Alternatively, you can bring in tokens by using the **Stream Metadata** button.

+

+

There is an extra line here.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796065912>:

> +1. Select **Generate Mappings**. This adds a row for mapping the value **Pump** that was present in the selected stream.

+

+1. In **Map To**, enter **Pump State**.

+

+1. Select **{Id} - A**, and if it is not already selected, choose **Use Existing Token Values**.

+

+1. Select **Next**.

+

+## <a name="gsAssetRules-configure-assets"></a> Configure assets

+

+Assign tokens values to asset fields.

+

+**Note**: You can enter  the `{` character to show a list of available tokens.

+

+1. In the **Configure Asset** panel, enter the following information.

+   - Id &ndash; **{Id}**

Need a blank line after each bullet and number.

________________________________

In content/overview/get-started/gs-asset-rules.md<https://github.com/osisoft/OCS-Docs/pull/823#discussion_r796066516>:

> +

+Assign tokens values to asset fields.

+

+**Note**: You can enter  the `{` character to show a list of available tokens.

+

+1. In the **Configure Asset** panel, enter the following information.

+   - Id &ndash; **{Id}**

+   - Name &ndash; **{Equipment}{Id}**

+   - Description &ndash; **{Region} {Site} Pump State**

+1. Select  **Next**.

+

+## <a name="gsAssetRules-preview-assets"></a> Preview assets

+

+Display a preview of the assets that will be created by this rule.

+

+1. Use the view selection at upper right to toggle between list and table view of the assets. The **Asset Preview** panel at left shows the rule details and statistics.

Needs a blank line.

—
Reply to this email directly, view it on GitHub<https://github.com/osisoft/OCS-Docs/pull/823#pullrequestreview-868417341>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQ6A5CDA6YQTAP7XTTJPJQTUY33DFANCNFSM5NHK3DDQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

__________________________________________________________________

AVEVA Group plc is registered in England at High Cross, Madingley Road, Cambridge, England CB3 0HB. Number 2937296.

2022-01-31 21:24 UTC, joyceseng commented on content/overview/get-started/gs-asset-rules.md
> +   - `Name` &ndash; **MyData.AssetRule**
I think I fixed the things you caught!

2022-01-31 21:27 UTC, osisoft-mbishop approved these changes
@joyceseng , you indeed added breaks between bullets. Looks good for merge.

2022-01-31 21:39 UTC, joyceseng commented
OMG! I am so relieved!

From: Mark B ***@***.***>
Sent: Monday, January 31, 2022 1:28 PM
To: osisoft/OCS-Docs ***@***.***>
Cc: Joyce Simmonds ***@***.***>; Mention ***@***.***>
Subject: Re: [osisoft/OCS-Docs] Add gsassetrules (PR #823)

CAUTION - This message originated outside AVEVA

@osisoft-mbishop approved this pull request.

@joyceseng<https://github.com/joyceseng> , you indeed added breaks between bullets. Looks good for merge.

—
Reply to this email directly, view it on GitHub<https://github.com/osisoft/OCS-Docs/pull/823#pullrequestreview-868436932>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQ6A5CF3CDKV4ERFVJ6LKH3UY35GDANCNFSM5NHK3DDQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

__________________________________________________________________

AVEVA Group plc is registered in England at High Cross, Madingley Road, Cambridge, England CB3 0HB. Number 2937296.

2022-02-03 19:40 UTC, merged

2022-02-04 17:33 UTC, joyceseng commented
Thank you, Mark!

From: Mark B ***@***.***>
Sent: Thursday, February 3, 2022 11:40 AM
To: osisoft/OCS-Docs ***@***.***>
Cc: Joyce Simmonds ***@***.***>; Mention ***@***.***>
Subject: Re: [osisoft/OCS-Docs] Add gsassetrules (PR #823)

CAUTION - This message originated outside AVEVA

Merged #823<https://github.com/osisoft/OCS-Docs/pull/823> into Development.

—
Reply to this email directly, view it on GitHub<https://github.com/osisoft/OCS-Docs/pull/823#event-6005223724>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQ6A5CAK5VLNWSNVGNMILRLUZLK2BANCNFSM5NHK3DDQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

__________________________________________________________________

AVEVA Group plc is registered in England at High Cross, Madingley Road, Cambridge, England CB3 0HB. Number 2937296.