Community roles updates
osisoft/OCS-Docs pull request #833
Opened 2022-02-12 01:05 UTC by osisoft-mbishop

@afloresOSI , this is a draft PR for reviewing https://dev.azure.com/osieng/engineering/_workitems/edit/288411. I have no intent of merging it for now.

2022-02-16 22:36 UTC, afloresOSI requested changes
The organization is a big improvement! I have some comments and suggestions for a few things.

2022-02-16 22:36 UTC, afloresOSI commented on content/communities/includes/enable-stream-sharing-permissions.md
> +To share data into a Community and provide access to this data for external tenants, a user with the **Share** permission on one or more streams must share the stream into a Community that they have
```suggestion
To share data into a community and provide access to this data for external tenants, a user with the **Share** permission on one or more streams must share the stream into a community that they have read access to. By default, the [Tenant Data Steward](xref:ccRoles#tenant-roles) role is intended for users in the tenant to share resources with other external tenants using communities. However, the Tenant Data Steward role is not assigned Share privileges on streams by default. Therefore, a Tenant Administrator or another user assigned **Manage Permissions** on the streams must first grant the Tenant Data Steward role, or another roles, the **Share** privilege on streams before they can be shared by users within that role. 
```

2022-02-16 22:36 UTC, afloresOSI commented on content/communities/includes/enable-stream-sharing-permissions.md
> +If you want to configure different roles to allow different data stewards to share different sets of data, you can accomplish this by not using the default Tenant Data Steward role and instead create
```suggestion
To configure different roles to allow different data stewards to share different sets of data, do not use the default Tenant Data Steward role and instead create the number of roles needed to manage this within your organization. Then repeat the steps above to grant the share permission for those roles on the specific sets of streams/data that each role will manage. For instructions on how to allow stream sharing, see [Manage permissions](xref:manage-streams#manage-permissions).
```

2022-02-16 22:36 UTC, afloresOSI commented on content/communities/community-manage-sds-permissions-create.md
> +[!include[enable stream sharing permissions](includes/enable-stream-sharing-permissions.md)]
If we were staying in GitHub for authoring, I would ask that you document this method of sharing content in the Wiki.

2022-02-16 22:36 UTC, afloresOSI commented on content/communities/community-data-sharing.md
> +After a community is established, Community Members can view which data streams their tenant has shared or view which streams another tenant has shared.  Community Members with additional sharing per
```suggestion
After a community is established, Community Members can view data streams their tenant or another tenant has shared.  Community Members with additional sharing permissions can share data streams with a community. 
```

2022-02-16 22:36 UTC, afloresOSI commented on content/communities/community-view-shared-data.md
> +After a stream is shared within a community, any [Community Member](xref:ccRoles#community-member-role-preview) can visualize it within a chart from the `Trend` page as if it were a data stream from
```suggestion
After a stream is shared within a community, any [Community Member](xref:ccRoles#community-member-role-preview) can visualize it within the `Trend` page as if it were a data stream from their own tenant. For more information on how to visualize data from a community within a trending session, see <xref:GettingStartedWithTrendData>.
```

2022-02-16 22:36 UTC, afloresOSI commented on content/set-up/roles/roles-concept.md
> +Some default tenant roles—Tenant Data Steward, Tenant Viewer, and Community Administrator—are assigned no permissions by default. Instead, these roles are intended to be customized for specialized us
```suggestion
Some default tenant roles—Tenant Data Steward, Tenant Viewer, and Community Administrator—are assigned no permissions by default. Instead, these roles are intended to be customized for specialized user roles in within OCS; you must assign these roles permissions for individual system resources to best suit your organization. 
```

2022-02-16 22:36 UTC, afloresOSI commented on content/set-up/roles/roles-concept.md
> +- Tenant Data Steward – Assign to data stewards, which are users that share data streams from the tenant's Sequential Data Store within a community.
```suggestion
- Tenant Data Steward – Assign to data stewards, who share data streams from the tenant's Sequential Data Store within a community.
```

2022-02-16 22:36 UTC, afloresOSI commented on content/set-up/roles/roles-concept.md
> +- Community Administrator – Assign to community administrators, which are users that moderate a community within the tenant. For more information, see [Community administrators](#community-administra
```suggestion
- Community Administrator – Assign to community administrators, who moderate a community within the tenant. For more information, see [Community administrators](#community-administrators-preview).
```

2022-02-16 22:36 UTC, afloresOSI commented on content/set-up/roles/roles-concept.md
> +When a user creates or joins a new community, they are prompted to assign new community administration permissions to one or more existing roles. All users from your tenant that are assigned these ro
When they join a community?

2022-02-17 03:18 UTC, osisoft-mbishop commented on content/communities/communities.md
> +Establish a community by creating it and then inviting your trusted business partners to join from their tenant. Each invitation is a three-way handshake. The Tenant Administrator that established th
Yeah, I like your corrections. I'm going to take your suggestions, and I'll also try to take another pass to shorten it even more later. These were some edits that a product manager wanted, but he tends to overwrite. However, he was very adament that we use "trusted business partner" rather than just "business partner".

2022-02-17 03:20 UTC, osisoft-mbishop commented on content/communities/communities.md
>  ## Community diagram
Yes, much better heading!

2022-02-17 03:25 UTC, osisoft-mbishop commented on content/communities/communities.md
>  ![Community diagram](images/community-diagram.svg)
Can you take a screencap and show me what it looks like? This is what it looks like on my end--sounds like there might be some kind of issue:

However, yes, I can improve the diagram. I'll use some more neutral colors on the data and then label them with some letters, just like the screenshot legend earlier in the sprint..

2022-02-17 03:29 UTC, osisoft-mbishop commented on content/set-up/roles/roles-concept.md
> +When a user creates or joins a new community, they are prompted to assign new community administration permissions to one or more existing roles. All users from your tenant that are assigned these ro
```suggestion
When a tenant creates or joins a new community, they are prompted to assign new community administration permissions to one or more existing roles. All users from your tenant that are assigned these roles inherit administrative permissions within the community, including the following actions:
```

2022-02-17 03:35 UTC, osisoft-mbishop commented on content/communities/community-setup.md
> +Establish a community by creating it and then inviting your trusted business partners to join from their tenant. Each invitation is a three-way handshake. The [Tenant Administrator](xref:ccRoles#tena
Ok, I'll shorten it up here as well.

2022-02-17 03:36 UTC, osisoft-mbishop commented on content/communities/community-manage-sds-permissions-create.md
> +[!include[enable stream sharing permissions](includes/enable-stream-sharing-permissions.md)]
Take a look here: https://dev.azure.com/osieng/engineering/_wiki/wikis/team-content/25154/Content-Reuse

2022-03-25 21:30 UTC, closed without merging