Pbi 287191 toc restructure update
osisoft/OCS-Docs pull request #844
Opened 2022-03-25 15:34 UTC by jasnames

Includes toc reorg, new landing pages, three new info tab pages, and some fixes along the way (another indent issue like Mark fixed on other topics, some incorrectly displaying asterisks, etc.)

2022-04-01 18:33 UTC, afloresOSI requested changes
I have a couple of edits. Overall, this will be a welcome change.

2022-04-01 19:34 UTC, afloresOSI submitted a review, later dismissed

2022-04-04 15:23 UTC, jasnames commented
@afloresOSI @osisoft-mbishop Need a new review approval to merge after Mark's updates

2022-04-04 15:30 UTC, afloresOSI approved these changes

2022-04-04 15:39 UTC, merged