Vtouati pbi 298778 GitHub QA
osisoft/OCS-Docs pull request #854
Opened 2022-04-04 19:03 UTC by VictoriaTouati-AVEVA

2022-04-04 19:28 UTC, afloresOSI requested changes
Minor wording edits. I

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +Saved transfers can be edited by adding or removing AF elements and/or PI points.
```suggestion
You can edit saved transfers by adding or removing AF elements and/or PI points.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +Perform these steps to edit an existing transfer:
```suggestion
To edit an existing transfer, follow these steps:
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. Click the **View/Edit Transfer** button.
```suggestion
1. Select **View/Edit Transfer**.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. In the transfer pane, select the **Edit Mode** toggle button.
```suggestion
1. In the transfer pane, select the **Edit Mode** toggle.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. (Optional) To add PI points to a transfer, enter search criteria on the **PI Point Search** tab, click **Search**, select desired PI points, then click **Add PI Points to Transfer**.
```suggestion
1. (Optional) To add PI points to a transfer, enter search criteria on the **PI Point Search** tab, select **Search**, select desired PI points, then select **Add PI Points to Transfer**. 
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. (Optional) To add AF elements to a transfer, enter search criteria on the **AF Elements Search** tab, click **Search**, select desired PI points, then click **Add AF Elements to Transfer**.
```suggestion
1. (Optional) To add AF elements to a transfer, enter search criteria on the **AF Elements Search** tab, select **Search**, select desired PI points, and then select **Add AF Elements to Transfer**.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. (Optional) Click **Undo Last Point Removal** to add the removed PI points back to the transfer.
```suggestion
1. (Optional)  To add the removed PI points back to the transfer, select **Undo Last Point Removal**.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. (Optional) Click **Undo Last Element Removal** to add the removed PI points back to the transfer.
```suggestion
1. (Optional) To add the removed PI points back to the transfer, select **Undo Last Element Removal** .
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/edit-transfer.md
> +1. After transfer edits are done, click **Save** to retain these changes and return to the `PI to OCS Agents` window.
```suggestion
1. After transfer edits are done, select **Save** to retain these changes and return to the `PI to OCS Agents` window.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 5  | Select the **Clear All Events** button to remove all search filters. |
```suggestion
| 5  | Select **Clear All Events** to remove all search filters. |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 6  | Select the **Export** button to save a copy of the health event messages to a .csv file.                               |
```suggestion
| 6  | Select **Export** to save a copy of the health event messages to a .csv file.                               |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 1  | The severity level of the log message. To filter by a particular severity level (Critical, Error, Warning, Information, Debug or Trace), click the filter icon and select one or more severity l
```suggestion
| 1  | The severity level of the log message. To filter by a particular severity level (Critical, Error, Warning, Information, Debug or Trace), select the filter icon and select one or more severity levels.        |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 2  | The source of an error message. To filter by source (agent, PI point indexing or AF indexing), click the filter icon and select one or more sources.  |
```suggestion
| 2  | The source of an error message. To filter by source (agent, PI point indexing or AF indexing), select the filter icon and select one or more sources.  |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 3  | The date of the event. To filter log messages by a particular date and/or time, click the filter icon, then enter the date and or time in Month 00, 000 00:00:00 PM format.  |
```suggestion
| 3  | The date of the event. To filter log messages by a particular date and/or time, select the filter icon, then enter the date and/or time in `Month 00, 000 00:00:00 PM` format.  |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +| 4  | The actual log message. To filter by a word or phrase, click the filter icon, then enter the word or phrase.      |
```suggestion
| 4  | The actual log message. To filter by a word or phrase, select the filter icon, then enter the word or phrase.      |
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
> +1. (Optional) To view more information about an agent's status, select the **Agent Health Events** button.
```suggestion
1. (Optional) To view more information about an agent's status, select **Agent Health Events**.
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
> +1. (Optional) To see more information about log messages for the transfer, select the **Logs** button. See [Tenant log messages](xref:download-tenant-log) for more information.
```suggestion
1. (Optional) To see more information about log messages for the transfer, select **Logs**. See [Tenant log messages](xref:download-tenant-log) for more information. 
```

2022-04-04 19:28 UTC, afloresOSI commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
> +1. (Optional) Click the `Transfer Metrics` tab to view transfer progress and metrics for stream and/or asset creation. See [Overview of transfer metrics](xref:overview-metrics) for more information.
```suggestion
1. (Optional) To view transfer progress and metrics for stream and/or asset creation, select the `Transfer Metrics` tab. See [Overview of transfer metrics](xref:overview-metrics) for more information. 
```

2022-04-04 21:22 UTC, jasnames requested changes
See suggestions. Other than what Angela already suggested, mostly just consistency of pane vs tab. Looks good!

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Stream Update Errors | Number of errors generated while updating streams. See the `Transfer Overview` section on the `Manage Agent` pane for error details. |
```suggestion
| Stream Update Errors | Number of errors generated while updating streams. See the `Transfer Overview` section on the **Manage Agent** tab for error details. |
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Stream Update Errors | Number of errors generated while updating streams. See the `Transfer Overview` section on the `Manage Agent` pane for error details. |
```suggestion
| Stream Update Errors | Number of errors generated while updating streams. See the `Transfer Overview` section on the **Manage Agent** tab for error details. |
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Stream Deletion Errors | Number of errors generated during stream deletion. See the `Transfer Overview` section on the `Manage Agent` pane for error details. |
```suggestion
| Stream Deletion Errors | Number of errors generated during stream deletion. See the `Transfer Overview` section on the **Manage Agent** tab for error details. |
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Stream Deletion Errors | Number of errors generated during stream deletion. See the `Transfer Overview` section on the `Manage Agent` pane for error details. |
```suggestion
| Stream Deletion Errors | Number of errors generated during stream deletion. See the `Transfer Overview` section on the **Manage Agent** tab for error details. |
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Asset Deletion Errors | The number of errors generated during asset deletion. See the `Transfer Overview` section on the `Manage Agent` pane for error details.
```suggestion
| Asset Deletion Errors | The number of errors generated during asset deletion. See the `Transfer Overview` section on the **Manage Agent** tab for error details.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +| Asset Deletion Errors | The number of errors generated during asset deletion. See the `Transfer Overview` section on the `Manage Agent` pane for error details.
```suggestion
| Asset Deletion Errors | The number of errors generated during asset deletion. See the `Transfer Overview` section on the **Manage Agent** tab for error details.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/data-transfer-statuses.md
> +The status and progress of a data transfer is shown in the Transfer Overview section of the Manage Agent pane. The following table lists these data statuses and their meanings.
```suggestion
The status and progress of a data transfer is shown in the `Transfer Overview` section of the **Manage Agent** tab. The following table lists these data statuses and their meanings.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/data-transfer-statuses.md
> +The status and progress of a data transfer is shown in the Transfer Overview section of the Manage Agent pane. The following table lists these data statuses and their meanings.
```suggestion
The status and progress of a data transfer is shown in the `Transfer Overview` section of the **Manage Agent** tab. The following table lists these data statuses and their meanings.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +The Health Events window provides information about an agent's activity and current status. Health events are based on log messages. You can sort messages by severity, source, time and message conten
```suggestion
The `Health Events` window provides information about an agent's activity and current status. Health events are based on log messages. You can sort messages by severity, source, time and message content.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +The Health Events window provides information about an agent's activity and current status. Health events are based on log messages. You can sort messages by severity, source, time and message conten
```suggestion
The `Health Events` window provides information about an agent's activity and current status. Health events are based on log messages. You can sort messages by severity, source, time and message content.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +The following table provides descriptions to the numbered elements in the Health Events window.
```suggestion
The following table provides descriptions to the numbered elements in the `Health Events` window.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/health-events-window.md
> +The following table provides descriptions to the numbered elements in the Health Events window.
```suggestion
The following table provides descriptions to the numbered elements in the `Health Events` window.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +The `Transfer Metrics` pane displays details about a transfer's progress by server connection. Metrics for streaming and historical events and the progress of stream and asset creation are shown.
```suggestion
The **Transfer Metrics** tab displays details about a transfer's progress by server connection. Metrics for streaming and historical events and the progress of stream and asset creation are shown. 
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +The `Transfer Metrics` pane displays details about a transfer's progress by server connection. Metrics for streaming and historical events and the progress of stream and asset creation are shown.
```suggestion
The **Transfer Metrics** tab displays details about a transfer's progress by server connection. Metrics for streaming and historical events and the progress of stream and asset creation are shown. 
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +The following table provides a description of the fields in the `Transfer Metrics` pane.
```suggestion
The following table provides a description of the fields in the **Transfer Metrics** tab.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/overview-metrics.md
> +The following table provides a description of the fields in the `Transfer Metrics` pane.
```suggestion
The following table provides a description of the fields in the **Transfer Metrics** tab.
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
> +**Note:** If you have configured an AF server, you will not be able to create a transfer until AF indexing is complete. AF indexing status is listed on the `Manage Agent` pane in the `PI to OCS Agent
```suggestion
**Note:** If you have configured an AF server, you will not be able to create a transfer until AF indexing is complete. AF indexing status is listed on the **Manage Agent** tab in the `PI to OCS Agents` window. The following image shows AF indexing in progress:
```

2022-04-04 21:22 UTC, jasnames commented on content/add-organize-data/collect-data/connectors/pi-to-ocs/pi-to-ocs-data-transfers/transfer-data-to-ocs.md
> +**Note:** If you have configured an AF server, you will not be able to create a transfer until AF indexing is complete. AF indexing status is listed on the `Manage Agent` pane in the `PI to OCS Agent
```suggestion
**Note:** If you have configured an AF server, you will not be able to create a transfer until AF indexing is complete. AF indexing status is listed on the **Manage Agent** tab in the `PI to OCS Agents` window. The following image shows AF indexing in progress:
```

2022-04-05 14:00 UTC, afloresOSI approved these changes

2022-05-03 16:23 UTC, jasnames approved these changes

2022-05-13 15:21 UTC, jasnames approved these changes

2022-05-13 16:37 UTC, merged