Merge latest updates from Infrastructure.
osisoft/OCS-Docs pull request #953
Opened 2022-09-12 15:27 UTC by stephenbelt

This PR is to merge the latest updates from Infrastructure.  2 updates of note:

1.  Examples are added for all api routes.
2. Namespaces are noted to NOT allow leading and trailing white space.

2022-09-12 18:40 UTC, jasnames requested changes
There seems to be a mapping and duplication issue. This PR adds folders for content and system that duplicate the content in tenant. We only want the files in the tenant folder.

content-service-blog = tenant-service-blog
system-features = tenant-features
system-namespaces = tenant-namespaces
system-root-access-control = tenant-root-access-control
system-tenant = tenant-tenants

Other than that, just a few minor grammar updates and I need to know the ADH values for a few of these items for when I migrate the content over.

2022-09-15 15:37 UTC, stephenbelt commented on content/api-reference/tenant/tenant-service-blog.md
> +    "Content": "This entry is here for to show the example.",
Update applied to Infrastructure source.

2022-09-15 15:42 UTC, stephenbelt commented on content/api-reference/tenant/tenant-namespaces.md
> +    "Self": "https://dat-b.osipi.com/api/v1/tenants/00c97c8b-8f60-4f29-af71-3178c414e7a0/namespaces/Namespace1",
https://euno.datahub.connect.aveva.com/ is the base address for Europe in ADH Prod.

2022-09-22 15:58 UTC, stephenbelt commented
Due to the mapping issue identified by @jasnames, I am going to abandon this PR.  A new PR is open in DocuPipe repos to repair the mappings, and when that is complete, I will open a new PR here.

2022-09-22 15:58 UTC, closed without merging