Two New Topics
osisoft/OCS-Docs pull request #998
Opened 2022-12-09 16:16 UTC by matthewcharles27

New topics for removing assets and asset types added. TOC updated.

2022-12-12 23:13 UTC, jasnames requested changes

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +1. From the **Assets/Asset** Types dropdown list, select **Assets**.
```suggestion
1. From the **Assets/Asset Types** selector, select **Assets**.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +1. From the **Assets/Asset** Types dropdown list, select **Asset Types**.
```suggestion
1. From the **Assets/Asset Types** selector, select **Assets**.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +**Note:** You may receive an error message when attempting to delete asset types. Only the creator of the asset type or a user with access can delete an asset type.
```suggestion
**Note:** You may receive an error message when attempting to delete assets. Only the creator of the asset or a user with access can delete an asset.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +1. Select the checkboxes for the Assets you want to remove.
```suggestion
1. Select the checkboxes for the assets you want to remove.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +1. Select the checkbox for the Asset you want to remove.
```suggestion
1. Select the checkbox for the asset you want to remove.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +1. Select **More Options**, then select **Remove**.
```suggestion
1. Select **More options** ![More options icon](../../../_icons/default/dots-vertical.svg) in the `Asset Details` pane, then select **Remove**.
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-assets.md
> +To remove a multiple assets:
```suggestion
To remove multiple assets:
```

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-asset-types.md
> +1. From the **Assets/Asset** Types dropdown list, select **Asset Types**.
Some of our topics use the dropdown term and some say selector, but since selector is what is in the hover text, I think that works better. Plus it's parallel to the create topic. Either way "Types" should be part of the bolding. :)

2022-12-12 23:13 UTC, jasnames commented on content/add-organize-data/organize-data/assets/remove-asset-types.md
> +1. Select **More Options**, then select **Remove**.
There's two "More options" on the screen. "... in the right pane" would be fine too.

2022-12-13 18:21 UTC, matthewcharles27 commented on content/add-organize-data/organize-data/assets/remove-asset-types.md
> +1. From the **Assets/Asset** Types dropdown list, select **Asset Types**.
Thanks, Jason. I agree with this and I actually took most of the instructions directly from the previous topics, so I'll make sure those are cleaned up, too.

2022-12-13 18:34 UTC, matthewcharles27 commented on content/add-organize-data/organize-data/assets/remove-asset-types.md
> +1. Select **More Options**, then select **Remove**.
Good catch! I thought the other more options got covered up; didn't realize it just moved.

2022-12-14 20:02 UTC, afloresOSI approved these changes

2022-12-14 20:15 UTC, jasnames approved these changes

2022-12-14 20:20 UTC, merged